// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ch3/ex9.proto

package uk.me.uohiro.protobuf.model.ch3.ex9;

public final class FilmProto {
  private FilmProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
    registry.add(uk.me.uohiro.protobuf.model.ch3.ex9.TerrorFilm.film);
    registry.add(uk.me.uohiro.protobuf.model.ch3.ex9.ScienceFictionFilm.film);
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ch3_ex9_Character_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ch3_ex9_Character_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ch3_ex9_Film_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ch3_ex9_Film_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ch3_ex9_Film_RolesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ch3_ex9_Film_RolesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ch3_ex9_TerrorFilm_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ch3_ex9_TerrorFilm_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ch3_ex9_ScienceFictionFilm_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ch3_ex9_ScienceFictionFilm_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rch3/ex9.proto\022\007ch3.ex9\"g\n\tCharacter\022\014\n" +
      "\004name\030\001 \002(\t\022\r\n\005birth\030\002 \002(\003\022\031\n\017laser_gun_" +
      "model\030\003 \001(\tH\000\022\033\n\021laser_sword_power\030\004 \001(\005" +
      "H\000B\005\n\003has\"\377\001\n\004Film\022\r\n\005title\030\001 \002(\t\022\020\n\010dir" +
      "ector\030\002 \002(\t\022\020\n\010producer\030\003 \002(\t\022\024\n\014release" +
      "_date\030\004 \001(\t\022\'\n\005roles\030\005 \003(\0132\030.ch3.ex9.Fil" +
      "m.RolesEntry\022=\n\020producer_company\030\006 \002(\0162\032" +
      ".ch3.ex9.ProducerCompanies:\007UNKNOWN\032@\n\nR" +
      "olesEntry\022\013\n\003key\030\001 \001(\t\022!\n\005value\030\002 \001(\0132\022." +
      "ch3.ex9.Character:\0028\001*\004\0102\020d\"S\n\nTerrorFil" +
      "m\022\023\n\013has_zombies\030\001 \001(\01020\n\004film\022\r.ch3.ex9" +
      ".Film\0302 \001(\0132\023.ch3.ex9.TerrorFilm\"a\n\022Scie" +
      "nceFictionFilm\022\021\n\thas_jedis\030\001 \001(\01028\n\004fil" +
      "m\022\r.ch3.ex9.Film\0303 \001(\0132\033.ch3.ex9.Science" +
      "FictionFilm*M\n\021ProducerCompanies\022\013\n\007UNKN" +
      "OWN\020\000\022\017\n\013WARNER_BROS\020\001\022\r\n\tPARAMOUNT\020\002\022\013\n" +
      "\007NETFLIX\020\003B4\n#uk.me.uohiro.protobuf.mode" +
      "l.ch3.ex9B\tFilmProtoH\001P\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ch3_ex9_Character_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ch3_ex9_Character_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ch3_ex9_Character_descriptor,
        new java.lang.String[] { "Name", "Birth", "LaserGunModel", "LaserSwordPower", "Has", });
    internal_static_ch3_ex9_Film_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ch3_ex9_Film_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ch3_ex9_Film_descriptor,
        new java.lang.String[] { "Title", "Director", "Producer", "ReleaseDate", "Roles", "ProducerCompany", });
    internal_static_ch3_ex9_Film_RolesEntry_descriptor =
      internal_static_ch3_ex9_Film_descriptor.getNestedTypes().get(0);
    internal_static_ch3_ex9_Film_RolesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ch3_ex9_Film_RolesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_ch3_ex9_TerrorFilm_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ch3_ex9_TerrorFilm_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ch3_ex9_TerrorFilm_descriptor,
        new java.lang.String[] { "HasZombies", });
    internal_static_ch3_ex9_ScienceFictionFilm_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_ch3_ex9_ScienceFictionFilm_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ch3_ex9_ScienceFictionFilm_descriptor,
        new java.lang.String[] { "HasJedis", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
