// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ch10/ex1/version.proto

package uk.me.uohiro.protobuf.model.ch10.ex1.v2;

public final class VersioningAPIProto {
  private VersioningAPIProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ch10_ex1_HelloRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ch10_ex1_HelloRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ch10_ex1_Name_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ch10_ex1_Name_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ch10_ex1_HelloResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ch10_ex1_HelloResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026ch10/ex1/version.proto\022\010ch10.ex1\"a\n\014He" +
      "lloRequest\022\030\n\020english_greeting\030\001 \001(\t\022\034\n\004" +
      "name\030\002 \001(\0132\016.ch10.ex1.Name\022\031\n\021japanese_g" +
      "reeting\030\003 \001(\t\"-\n\004Name\022\022\n\nfirst_name\030\001 \001(" +
      "\t\022\021\n\tlast_name\030\002 \001(\t\">\n\rHelloResponse\022\025\n" +
      "\renglish_reply\030\001 \001(\t\022\026\n\016japanese_reply\030\002" +
      " \001(\t2N\n\017GreetingService\022;\n\010SayHello\022\026.ch" +
      "10.ex1.HelloRequest\032\027.ch10.ex1.HelloResp" +
      "onseBA\n\'uk.me.uohiro.protobuf.model.ch10" +
      ".ex1.v2B\022VersioningAPIProtoH\001P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ch10_ex1_HelloRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ch10_ex1_HelloRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ch10_ex1_HelloRequest_descriptor,
        new java.lang.String[] { "EnglishGreeting", "Name", "JapaneseGreeting", });
    internal_static_ch10_ex1_Name_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ch10_ex1_Name_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ch10_ex1_Name_descriptor,
        new java.lang.String[] { "FirstName", "LastName", });
    internal_static_ch10_ex1_HelloResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ch10_ex1_HelloResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ch10_ex1_HelloResponse_descriptor,
        new java.lang.String[] { "EnglishReply", "JapaneseReply", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
