// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ch10/ex3/field_mask.proto

package uk.me.uohiro.protobuf.model.ch10.ex3;

/**
 * Protobuf type {@code ch10.ex3.FieldMaskRequest}
 */
public  final class FieldMaskRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ch10.ex3.FieldMaskRequest)
    FieldMaskRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FieldMaskRequest.newBuilder() to construct.
  private FieldMaskRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FieldMaskRequest() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private FieldMaskRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.google.protobuf.StringValue.Builder subBuilder = null;
            if (stringValue_ != null) {
              subBuilder = stringValue_.toBuilder();
            }
            stringValue_ = input.readMessage(com.google.protobuf.StringValue.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(stringValue_);
              stringValue_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            com.google.protobuf.Int32Value.Builder subBuilder = null;
            if (int32Value_ != null) {
              subBuilder = int32Value_.toBuilder();
            }
            int32Value_ = input.readMessage(com.google.protobuf.Int32Value.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(int32Value_);
              int32Value_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            uk.me.uohiro.protobuf.model.ch10.ex3.FieldMaskRequest.NestedMessage.Builder subBuilder = null;
            if (nestedMessage_ != null) {
              subBuilder = nestedMessage_.toBuilder();
            }
            nestedMessage_ = input.readMessage(uk.me.uohiro.protobuf.model.ch10.ex3.FieldMaskRequest.NestedMessage.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(nestedMessage_);
              nestedMessage_ = subBuilder.buildPartial();
            }

            break;
          }
          case 34: {
            com.google.protobuf.FieldMask.Builder subBuilder = null;
            if (mask_ != null) {
              subBuilder = mask_.toBuilder();
            }
            mask_ = input.readMessage(com.google.protobuf.FieldMask.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(mask_);
              mask_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return uk.me.uohiro.protobuf.model.ch10.ex3.FieldMaskAPIProto.internal_static_ch10_ex3_FieldMaskRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return uk.me.uohiro.protobuf.model.ch10.ex3.FieldMaskAPIProto.internal_static_ch10_ex3_FieldMaskRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            uk.me.uohiro.protobuf.model.ch10.ex3.FieldMaskRequest.class, uk.me.uohiro.protobuf.model.ch10.ex3.FieldMaskRequest.Builder.class);
  }

  public interface NestedMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ch10.ex3.FieldMaskRequest.NestedMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.google.protobuf.StringValue string_value = 1;</code>
     */
    boolean hasStringValue();
    /**
     * <code>.google.protobuf.StringValue string_value = 1;</code>
     */
    com.google.protobuf.StringValue getStringValue();
    /**
     * <code>.google.protobuf.StringValue string_value = 1;</code>
     */
    com.google.protobuf.StringValueOrBuilder getStringValueOrBuilder();

    /**
     * <code>.google.protobuf.Int32Value int32_value = 2;</code>
     */
    boolean hasInt32Value();
    /**
     * <code>.google.protobuf.Int32Value int32_value = 2;</code>
     */
    com.google.protobuf.Int32Value getInt32Value();
    /**
     * <code>.google.protobuf.Int32Value int32_value = 2;</code>
     */
    com.google.protobuf.Int32ValueOrBuilder getInt32ValueOrBuilder();
  }
  /**
   * Protobuf type {@code ch10.ex3.FieldMaskRequest.NestedMessage}
   */
  public  static final class NestedMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ch10.ex3.FieldMaskRequest.NestedMessage)
      NestedMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use NestedMessage.newBuilder() to construct.
    private NestedMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private NestedMessage() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private NestedMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.StringValue.Builder subBuilder = null;
              if (stringValue_ != null) {
                subBuilder = stringValue_.toBuilder();
              }
              stringValue_ = input.readMessage(com.google.protobuf.StringValue.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(stringValue_);
                stringValue_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              com.google.protobuf.Int32Value.Builder subBuilder = null;
              if (int32Value_ != null) {
                subBuilder = int32Value_.toBuilder();
              }
              int32Value_ = input.readMessage(com.google.protobuf.Int32Value.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(int32Value_);
                int32Value_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return uk.me.uohiro.protobuf.model.ch10.ex3.FieldMaskAPIProto.internal_static_ch10_ex3_FieldMaskRequest_NestedMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return uk.me.uohiro.protobuf.model.ch10.ex3.FieldMaskAPIProto.internal_static_ch10_ex3_FieldMaskRequest_NestedMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              uk.me.uohiro.protobuf.model.ch10.ex3.FieldMaskRequest.NestedMessage.class, uk.me.uohiro.protobuf.model.ch10.ex3.FieldMaskRequest.NestedMessage.Builder.class);
    }

    public static final int STRING_VALUE_FIELD_NUMBER = 1;
    private com.google.protobuf.StringValue stringValue_;
    /**
     * <code>.google.protobuf.StringValue string_value = 1;</code>
     */
    public boolean hasStringValue() {
      return stringValue_ != null;
    }
    /**
     * <code>.google.protobuf.StringValue string_value = 1;</code>
     */
    public com.google.protobuf.StringValue getStringValue() {
      return stringValue_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : stringValue_;
    }
    /**
     * <code>.google.protobuf.StringValue string_value = 1;</code>
     */
    public com.google.protobuf.StringValueOrBuilder getStringValueOrBuilder() {
      return getStringValue();
    }

    public static final int INT32_VALUE_FIELD_NUMBER = 2;
    private com.google.protobuf.Int32Value int32Value_;
    /**
     * <code>.google.protobuf.Int32Value int32_value = 2;</code>
     */
    public boolean hasInt32Value() {
      return int32Value_ != null;
    }
    /**
     * <code>.google.protobuf.Int32Value int32_value = 2;</code>
     */
    public com.google.protobuf.Int32Value getInt32Value() {
      return int32Value_ == null ? com.google.protobuf.Int32Value.getDefaultInstance() : int32Value_;
    }
    /**
     * <code>.google.protobuf.Int32Value int32_value = 2;</code>
     */
    public com.google.protobuf.Int32ValueOrBuilder getInt32ValueOrBuilder() {
      return getInt32Value();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (stringValue_ != null) {
        output.writeMessage(1, getStringValue());
      }
      if (int32Value_ != null) {
        output.writeMessage(2, getInt32Value());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (stringValue_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getStringValue());
      }
      if (int32Value_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getInt32Value());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof uk.me.uohiro.protobuf.model.ch10.ex3.FieldMaskRequest.NestedMessage)) {
        return super.equals(obj);
      }
      uk.me.uohiro.protobuf.model.ch10.ex3.FieldMaskRequest.NestedMessage other = (uk.me.uohiro.protobuf.model.ch10.ex3.FieldMaskRequest.NestedMessage) obj;

      boolean result = true;
      result = result && (hasStringValue() == other.hasStringValue());
      if (hasStringValue()) {
        result = result && getStringValue()
            .equals(other.getStringValue());
      }
      result = result && (hasInt32Value() == other.hasInt32Value());
      if (hasInt32Value()) {
        result = result && getInt32Value()
            .equals(other.getInt32Value());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasStringValue()) {
        hash = (37 * hash) + STRING_VALUE_FIELD_NUMBER;
        hash = (53 * hash) + getStringValue().hashCode();
      }
      if (hasInt32Value()) {
        hash = (37 * hash) + INT32_VALUE_FIELD_NUMBER;
        hash = (53 * hash) + getInt32Value().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static uk.me.uohiro.protobuf.model.ch10.ex3.FieldMaskRequest.NestedMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static uk.me.uohiro.protobuf.model.ch10.ex3.FieldMaskRequest.NestedMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static uk.me.uohiro.protobuf.model.ch10.ex3.FieldMaskRequest.NestedMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static uk.me.uohiro.protobuf.model.ch10.ex3.FieldMaskRequest.NestedMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static uk.me.uohiro.protobuf.model.ch10.ex3.FieldMaskRequest.NestedMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static uk.me.uohiro.protobuf.model.ch10.ex3.FieldMaskRequest.NestedMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static uk.me.uohiro.protobuf.model.ch10.ex3.FieldMaskRequest.NestedMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static uk.me.uohiro.protobuf.model.ch10.ex3.FieldMaskRequest.NestedMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static uk.me.uohiro.protobuf.model.ch10.ex3.FieldMaskRequest.NestedMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static uk.me.uohiro.protobuf.model.ch10.ex3.FieldMaskRequest.NestedMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static uk.me.uohiro.protobuf.model.ch10.ex3.FieldMaskRequest.NestedMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static uk.me.uohiro.protobuf.model.ch10.ex3.FieldMaskRequest.NestedMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(uk.me.uohiro.protobuf.model.ch10.ex3.FieldMaskRequest.NestedMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ch10.ex3.FieldMaskRequest.NestedMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ch10.ex3.FieldMaskRequest.NestedMessage)
        uk.me.uohiro.protobuf.model.ch10.ex3.FieldMaskRequest.NestedMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return uk.me.uohiro.protobuf.model.ch10.ex3.FieldMaskAPIProto.internal_static_ch10_ex3_FieldMaskRequest_NestedMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return uk.me.uohiro.protobuf.model.ch10.ex3.FieldMaskAPIProto.internal_static_ch10_ex3_FieldMaskRequest_NestedMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                uk.me.uohiro.protobuf.model.ch10.ex3.FieldMaskRequest.NestedMessage.class, uk.me.uohiro.protobuf.model.ch10.ex3.FieldMaskRequest.NestedMessage.Builder.class);
      }

      // Construct using uk.me.uohiro.protobuf.model.ch10.ex3.FieldMaskRequest.NestedMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (stringValueBuilder_ == null) {
          stringValue_ = null;
        } else {
          stringValue_ = null;
          stringValueBuilder_ = null;
        }
        if (int32ValueBuilder_ == null) {
          int32Value_ = null;
        } else {
          int32Value_ = null;
          int32ValueBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return uk.me.uohiro.protobuf.model.ch10.ex3.FieldMaskAPIProto.internal_static_ch10_ex3_FieldMaskRequest_NestedMessage_descriptor;
      }

      @java.lang.Override
      public uk.me.uohiro.protobuf.model.ch10.ex3.FieldMaskRequest.NestedMessage getDefaultInstanceForType() {
        return uk.me.uohiro.protobuf.model.ch10.ex3.FieldMaskRequest.NestedMessage.getDefaultInstance();
      }

      @java.lang.Override
      public uk.me.uohiro.protobuf.model.ch10.ex3.FieldMaskRequest.NestedMessage build() {
        uk.me.uohiro.protobuf.model.ch10.ex3.FieldMaskRequest.NestedMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public uk.me.uohiro.protobuf.model.ch10.ex3.FieldMaskRequest.NestedMessage buildPartial() {
        uk.me.uohiro.protobuf.model.ch10.ex3.FieldMaskRequest.NestedMessage result = new uk.me.uohiro.protobuf.model.ch10.ex3.FieldMaskRequest.NestedMessage(this);
        if (stringValueBuilder_ == null) {
          result.stringValue_ = stringValue_;
        } else {
          result.stringValue_ = stringValueBuilder_.build();
        }
        if (int32ValueBuilder_ == null) {
          result.int32Value_ = int32Value_;
        } else {
          result.int32Value_ = int32ValueBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof uk.me.uohiro.protobuf.model.ch10.ex3.FieldMaskRequest.NestedMessage) {
          return mergeFrom((uk.me.uohiro.protobuf.model.ch10.ex3.FieldMaskRequest.NestedMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(uk.me.uohiro.protobuf.model.ch10.ex3.FieldMaskRequest.NestedMessage other) {
        if (other == uk.me.uohiro.protobuf.model.ch10.ex3.FieldMaskRequest.NestedMessage.getDefaultInstance()) return this;
        if (other.hasStringValue()) {
          mergeStringValue(other.getStringValue());
        }
        if (other.hasInt32Value()) {
          mergeInt32Value(other.getInt32Value());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        uk.me.uohiro.protobuf.model.ch10.ex3.FieldMaskRequest.NestedMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (uk.me.uohiro.protobuf.model.ch10.ex3.FieldMaskRequest.NestedMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.StringValue stringValue_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> stringValueBuilder_;
      /**
       * <code>.google.protobuf.StringValue string_value = 1;</code>
       */
      public boolean hasStringValue() {
        return stringValueBuilder_ != null || stringValue_ != null;
      }
      /**
       * <code>.google.protobuf.StringValue string_value = 1;</code>
       */
      public com.google.protobuf.StringValue getStringValue() {
        if (stringValueBuilder_ == null) {
          return stringValue_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : stringValue_;
        } else {
          return stringValueBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.StringValue string_value = 1;</code>
       */
      public Builder setStringValue(com.google.protobuf.StringValue value) {
        if (stringValueBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          stringValue_ = value;
          onChanged();
        } else {
          stringValueBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue string_value = 1;</code>
       */
      public Builder setStringValue(
          com.google.protobuf.StringValue.Builder builderForValue) {
        if (stringValueBuilder_ == null) {
          stringValue_ = builderForValue.build();
          onChanged();
        } else {
          stringValueBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue string_value = 1;</code>
       */
      public Builder mergeStringValue(com.google.protobuf.StringValue value) {
        if (stringValueBuilder_ == null) {
          if (stringValue_ != null) {
            stringValue_ =
              com.google.protobuf.StringValue.newBuilder(stringValue_).mergeFrom(value).buildPartial();
          } else {
            stringValue_ = value;
          }
          onChanged();
        } else {
          stringValueBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue string_value = 1;</code>
       */
      public Builder clearStringValue() {
        if (stringValueBuilder_ == null) {
          stringValue_ = null;
          onChanged();
        } else {
          stringValue_ = null;
          stringValueBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue string_value = 1;</code>
       */
      public com.google.protobuf.StringValue.Builder getStringValueBuilder() {
        
        onChanged();
        return getStringValueFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.StringValue string_value = 1;</code>
       */
      public com.google.protobuf.StringValueOrBuilder getStringValueOrBuilder() {
        if (stringValueBuilder_ != null) {
          return stringValueBuilder_.getMessageOrBuilder();
        } else {
          return stringValue_ == null ?
              com.google.protobuf.StringValue.getDefaultInstance() : stringValue_;
        }
      }
      /**
       * <code>.google.protobuf.StringValue string_value = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> 
          getStringValueFieldBuilder() {
        if (stringValueBuilder_ == null) {
          stringValueBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder>(
                  getStringValue(),
                  getParentForChildren(),
                  isClean());
          stringValue_ = null;
        }
        return stringValueBuilder_;
      }

      private com.google.protobuf.Int32Value int32Value_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder> int32ValueBuilder_;
      /**
       * <code>.google.protobuf.Int32Value int32_value = 2;</code>
       */
      public boolean hasInt32Value() {
        return int32ValueBuilder_ != null || int32Value_ != null;
      }
      /**
       * <code>.google.protobuf.Int32Value int32_value = 2;</code>
       */
      public com.google.protobuf.Int32Value getInt32Value() {
        if (int32ValueBuilder_ == null) {
          return int32Value_ == null ? com.google.protobuf.Int32Value.getDefaultInstance() : int32Value_;
        } else {
          return int32ValueBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Int32Value int32_value = 2;</code>
       */
      public Builder setInt32Value(com.google.protobuf.Int32Value value) {
        if (int32ValueBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          int32Value_ = value;
          onChanged();
        } else {
          int32ValueBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Int32Value int32_value = 2;</code>
       */
      public Builder setInt32Value(
          com.google.protobuf.Int32Value.Builder builderForValue) {
        if (int32ValueBuilder_ == null) {
          int32Value_ = builderForValue.build();
          onChanged();
        } else {
          int32ValueBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Int32Value int32_value = 2;</code>
       */
      public Builder mergeInt32Value(com.google.protobuf.Int32Value value) {
        if (int32ValueBuilder_ == null) {
          if (int32Value_ != null) {
            int32Value_ =
              com.google.protobuf.Int32Value.newBuilder(int32Value_).mergeFrom(value).buildPartial();
          } else {
            int32Value_ = value;
          }
          onChanged();
        } else {
          int32ValueBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Int32Value int32_value = 2;</code>
       */
      public Builder clearInt32Value() {
        if (int32ValueBuilder_ == null) {
          int32Value_ = null;
          onChanged();
        } else {
          int32Value_ = null;
          int32ValueBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Int32Value int32_value = 2;</code>
       */
      public com.google.protobuf.Int32Value.Builder getInt32ValueBuilder() {
        
        onChanged();
        return getInt32ValueFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Int32Value int32_value = 2;</code>
       */
      public com.google.protobuf.Int32ValueOrBuilder getInt32ValueOrBuilder() {
        if (int32ValueBuilder_ != null) {
          return int32ValueBuilder_.getMessageOrBuilder();
        } else {
          return int32Value_ == null ?
              com.google.protobuf.Int32Value.getDefaultInstance() : int32Value_;
        }
      }
      /**
       * <code>.google.protobuf.Int32Value int32_value = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder> 
          getInt32ValueFieldBuilder() {
        if (int32ValueBuilder_ == null) {
          int32ValueBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder>(
                  getInt32Value(),
                  getParentForChildren(),
                  isClean());
          int32Value_ = null;
        }
        return int32ValueBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ch10.ex3.FieldMaskRequest.NestedMessage)
    }

    // @@protoc_insertion_point(class_scope:ch10.ex3.FieldMaskRequest.NestedMessage)
    private static final uk.me.uohiro.protobuf.model.ch10.ex3.FieldMaskRequest.NestedMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new uk.me.uohiro.protobuf.model.ch10.ex3.FieldMaskRequest.NestedMessage();
    }

    public static uk.me.uohiro.protobuf.model.ch10.ex3.FieldMaskRequest.NestedMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<NestedMessage>
        PARSER = new com.google.protobuf.AbstractParser<NestedMessage>() {
      @java.lang.Override
      public NestedMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new NestedMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<NestedMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<NestedMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public uk.me.uohiro.protobuf.model.ch10.ex3.FieldMaskRequest.NestedMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int STRING_VALUE_FIELD_NUMBER = 1;
  private com.google.protobuf.StringValue stringValue_;
  /**
   * <code>.google.protobuf.StringValue string_value = 1;</code>
   */
  public boolean hasStringValue() {
    return stringValue_ != null;
  }
  /**
   * <code>.google.protobuf.StringValue string_value = 1;</code>
   */
  public com.google.protobuf.StringValue getStringValue() {
    return stringValue_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : stringValue_;
  }
  /**
   * <code>.google.protobuf.StringValue string_value = 1;</code>
   */
  public com.google.protobuf.StringValueOrBuilder getStringValueOrBuilder() {
    return getStringValue();
  }

  public static final int INT32_VALUE_FIELD_NUMBER = 2;
  private com.google.protobuf.Int32Value int32Value_;
  /**
   * <code>.google.protobuf.Int32Value int32_value = 2;</code>
   */
  public boolean hasInt32Value() {
    return int32Value_ != null;
  }
  /**
   * <code>.google.protobuf.Int32Value int32_value = 2;</code>
   */
  public com.google.protobuf.Int32Value getInt32Value() {
    return int32Value_ == null ? com.google.protobuf.Int32Value.getDefaultInstance() : int32Value_;
  }
  /**
   * <code>.google.protobuf.Int32Value int32_value = 2;</code>
   */
  public com.google.protobuf.Int32ValueOrBuilder getInt32ValueOrBuilder() {
    return getInt32Value();
  }

  public static final int NESTED_MESSAGE_FIELD_NUMBER = 3;
  private uk.me.uohiro.protobuf.model.ch10.ex3.FieldMaskRequest.NestedMessage nestedMessage_;
  /**
   * <code>.ch10.ex3.FieldMaskRequest.NestedMessage nested_message = 3;</code>
   */
  public boolean hasNestedMessage() {
    return nestedMessage_ != null;
  }
  /**
   * <code>.ch10.ex3.FieldMaskRequest.NestedMessage nested_message = 3;</code>
   */
  public uk.me.uohiro.protobuf.model.ch10.ex3.FieldMaskRequest.NestedMessage getNestedMessage() {
    return nestedMessage_ == null ? uk.me.uohiro.protobuf.model.ch10.ex3.FieldMaskRequest.NestedMessage.getDefaultInstance() : nestedMessage_;
  }
  /**
   * <code>.ch10.ex3.FieldMaskRequest.NestedMessage nested_message = 3;</code>
   */
  public uk.me.uohiro.protobuf.model.ch10.ex3.FieldMaskRequest.NestedMessageOrBuilder getNestedMessageOrBuilder() {
    return getNestedMessage();
  }

  public static final int MASK_FIELD_NUMBER = 4;
  private com.google.protobuf.FieldMask mask_;
  /**
   * <code>.google.protobuf.FieldMask mask = 4;</code>
   */
  public boolean hasMask() {
    return mask_ != null;
  }
  /**
   * <code>.google.protobuf.FieldMask mask = 4;</code>
   */
  public com.google.protobuf.FieldMask getMask() {
    return mask_ == null ? com.google.protobuf.FieldMask.getDefaultInstance() : mask_;
  }
  /**
   * <code>.google.protobuf.FieldMask mask = 4;</code>
   */
  public com.google.protobuf.FieldMaskOrBuilder getMaskOrBuilder() {
    return getMask();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (stringValue_ != null) {
      output.writeMessage(1, getStringValue());
    }
    if (int32Value_ != null) {
      output.writeMessage(2, getInt32Value());
    }
    if (nestedMessage_ != null) {
      output.writeMessage(3, getNestedMessage());
    }
    if (mask_ != null) {
      output.writeMessage(4, getMask());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (stringValue_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getStringValue());
    }
    if (int32Value_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getInt32Value());
    }
    if (nestedMessage_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getNestedMessage());
    }
    if (mask_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getMask());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof uk.me.uohiro.protobuf.model.ch10.ex3.FieldMaskRequest)) {
      return super.equals(obj);
    }
    uk.me.uohiro.protobuf.model.ch10.ex3.FieldMaskRequest other = (uk.me.uohiro.protobuf.model.ch10.ex3.FieldMaskRequest) obj;

    boolean result = true;
    result = result && (hasStringValue() == other.hasStringValue());
    if (hasStringValue()) {
      result = result && getStringValue()
          .equals(other.getStringValue());
    }
    result = result && (hasInt32Value() == other.hasInt32Value());
    if (hasInt32Value()) {
      result = result && getInt32Value()
          .equals(other.getInt32Value());
    }
    result = result && (hasNestedMessage() == other.hasNestedMessage());
    if (hasNestedMessage()) {
      result = result && getNestedMessage()
          .equals(other.getNestedMessage());
    }
    result = result && (hasMask() == other.hasMask());
    if (hasMask()) {
      result = result && getMask()
          .equals(other.getMask());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasStringValue()) {
      hash = (37 * hash) + STRING_VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getStringValue().hashCode();
    }
    if (hasInt32Value()) {
      hash = (37 * hash) + INT32_VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getInt32Value().hashCode();
    }
    if (hasNestedMessage()) {
      hash = (37 * hash) + NESTED_MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getNestedMessage().hashCode();
    }
    if (hasMask()) {
      hash = (37 * hash) + MASK_FIELD_NUMBER;
      hash = (53 * hash) + getMask().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static uk.me.uohiro.protobuf.model.ch10.ex3.FieldMaskRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static uk.me.uohiro.protobuf.model.ch10.ex3.FieldMaskRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static uk.me.uohiro.protobuf.model.ch10.ex3.FieldMaskRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static uk.me.uohiro.protobuf.model.ch10.ex3.FieldMaskRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static uk.me.uohiro.protobuf.model.ch10.ex3.FieldMaskRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static uk.me.uohiro.protobuf.model.ch10.ex3.FieldMaskRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static uk.me.uohiro.protobuf.model.ch10.ex3.FieldMaskRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static uk.me.uohiro.protobuf.model.ch10.ex3.FieldMaskRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static uk.me.uohiro.protobuf.model.ch10.ex3.FieldMaskRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static uk.me.uohiro.protobuf.model.ch10.ex3.FieldMaskRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static uk.me.uohiro.protobuf.model.ch10.ex3.FieldMaskRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static uk.me.uohiro.protobuf.model.ch10.ex3.FieldMaskRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(uk.me.uohiro.protobuf.model.ch10.ex3.FieldMaskRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ch10.ex3.FieldMaskRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ch10.ex3.FieldMaskRequest)
      uk.me.uohiro.protobuf.model.ch10.ex3.FieldMaskRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return uk.me.uohiro.protobuf.model.ch10.ex3.FieldMaskAPIProto.internal_static_ch10_ex3_FieldMaskRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return uk.me.uohiro.protobuf.model.ch10.ex3.FieldMaskAPIProto.internal_static_ch10_ex3_FieldMaskRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              uk.me.uohiro.protobuf.model.ch10.ex3.FieldMaskRequest.class, uk.me.uohiro.protobuf.model.ch10.ex3.FieldMaskRequest.Builder.class);
    }

    // Construct using uk.me.uohiro.protobuf.model.ch10.ex3.FieldMaskRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (stringValueBuilder_ == null) {
        stringValue_ = null;
      } else {
        stringValue_ = null;
        stringValueBuilder_ = null;
      }
      if (int32ValueBuilder_ == null) {
        int32Value_ = null;
      } else {
        int32Value_ = null;
        int32ValueBuilder_ = null;
      }
      if (nestedMessageBuilder_ == null) {
        nestedMessage_ = null;
      } else {
        nestedMessage_ = null;
        nestedMessageBuilder_ = null;
      }
      if (maskBuilder_ == null) {
        mask_ = null;
      } else {
        mask_ = null;
        maskBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return uk.me.uohiro.protobuf.model.ch10.ex3.FieldMaskAPIProto.internal_static_ch10_ex3_FieldMaskRequest_descriptor;
    }

    @java.lang.Override
    public uk.me.uohiro.protobuf.model.ch10.ex3.FieldMaskRequest getDefaultInstanceForType() {
      return uk.me.uohiro.protobuf.model.ch10.ex3.FieldMaskRequest.getDefaultInstance();
    }

    @java.lang.Override
    public uk.me.uohiro.protobuf.model.ch10.ex3.FieldMaskRequest build() {
      uk.me.uohiro.protobuf.model.ch10.ex3.FieldMaskRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public uk.me.uohiro.protobuf.model.ch10.ex3.FieldMaskRequest buildPartial() {
      uk.me.uohiro.protobuf.model.ch10.ex3.FieldMaskRequest result = new uk.me.uohiro.protobuf.model.ch10.ex3.FieldMaskRequest(this);
      if (stringValueBuilder_ == null) {
        result.stringValue_ = stringValue_;
      } else {
        result.stringValue_ = stringValueBuilder_.build();
      }
      if (int32ValueBuilder_ == null) {
        result.int32Value_ = int32Value_;
      } else {
        result.int32Value_ = int32ValueBuilder_.build();
      }
      if (nestedMessageBuilder_ == null) {
        result.nestedMessage_ = nestedMessage_;
      } else {
        result.nestedMessage_ = nestedMessageBuilder_.build();
      }
      if (maskBuilder_ == null) {
        result.mask_ = mask_;
      } else {
        result.mask_ = maskBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof uk.me.uohiro.protobuf.model.ch10.ex3.FieldMaskRequest) {
        return mergeFrom((uk.me.uohiro.protobuf.model.ch10.ex3.FieldMaskRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(uk.me.uohiro.protobuf.model.ch10.ex3.FieldMaskRequest other) {
      if (other == uk.me.uohiro.protobuf.model.ch10.ex3.FieldMaskRequest.getDefaultInstance()) return this;
      if (other.hasStringValue()) {
        mergeStringValue(other.getStringValue());
      }
      if (other.hasInt32Value()) {
        mergeInt32Value(other.getInt32Value());
      }
      if (other.hasNestedMessage()) {
        mergeNestedMessage(other.getNestedMessage());
      }
      if (other.hasMask()) {
        mergeMask(other.getMask());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      uk.me.uohiro.protobuf.model.ch10.ex3.FieldMaskRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (uk.me.uohiro.protobuf.model.ch10.ex3.FieldMaskRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.google.protobuf.StringValue stringValue_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> stringValueBuilder_;
    /**
     * <code>.google.protobuf.StringValue string_value = 1;</code>
     */
    public boolean hasStringValue() {
      return stringValueBuilder_ != null || stringValue_ != null;
    }
    /**
     * <code>.google.protobuf.StringValue string_value = 1;</code>
     */
    public com.google.protobuf.StringValue getStringValue() {
      if (stringValueBuilder_ == null) {
        return stringValue_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : stringValue_;
      } else {
        return stringValueBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.StringValue string_value = 1;</code>
     */
    public Builder setStringValue(com.google.protobuf.StringValue value) {
      if (stringValueBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        stringValue_ = value;
        onChanged();
      } else {
        stringValueBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue string_value = 1;</code>
     */
    public Builder setStringValue(
        com.google.protobuf.StringValue.Builder builderForValue) {
      if (stringValueBuilder_ == null) {
        stringValue_ = builderForValue.build();
        onChanged();
      } else {
        stringValueBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue string_value = 1;</code>
     */
    public Builder mergeStringValue(com.google.protobuf.StringValue value) {
      if (stringValueBuilder_ == null) {
        if (stringValue_ != null) {
          stringValue_ =
            com.google.protobuf.StringValue.newBuilder(stringValue_).mergeFrom(value).buildPartial();
        } else {
          stringValue_ = value;
        }
        onChanged();
      } else {
        stringValueBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue string_value = 1;</code>
     */
    public Builder clearStringValue() {
      if (stringValueBuilder_ == null) {
        stringValue_ = null;
        onChanged();
      } else {
        stringValue_ = null;
        stringValueBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue string_value = 1;</code>
     */
    public com.google.protobuf.StringValue.Builder getStringValueBuilder() {
      
      onChanged();
      return getStringValueFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.StringValue string_value = 1;</code>
     */
    public com.google.protobuf.StringValueOrBuilder getStringValueOrBuilder() {
      if (stringValueBuilder_ != null) {
        return stringValueBuilder_.getMessageOrBuilder();
      } else {
        return stringValue_ == null ?
            com.google.protobuf.StringValue.getDefaultInstance() : stringValue_;
      }
    }
    /**
     * <code>.google.protobuf.StringValue string_value = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> 
        getStringValueFieldBuilder() {
      if (stringValueBuilder_ == null) {
        stringValueBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder>(
                getStringValue(),
                getParentForChildren(),
                isClean());
        stringValue_ = null;
      }
      return stringValueBuilder_;
    }

    private com.google.protobuf.Int32Value int32Value_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder> int32ValueBuilder_;
    /**
     * <code>.google.protobuf.Int32Value int32_value = 2;</code>
     */
    public boolean hasInt32Value() {
      return int32ValueBuilder_ != null || int32Value_ != null;
    }
    /**
     * <code>.google.protobuf.Int32Value int32_value = 2;</code>
     */
    public com.google.protobuf.Int32Value getInt32Value() {
      if (int32ValueBuilder_ == null) {
        return int32Value_ == null ? com.google.protobuf.Int32Value.getDefaultInstance() : int32Value_;
      } else {
        return int32ValueBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Int32Value int32_value = 2;</code>
     */
    public Builder setInt32Value(com.google.protobuf.Int32Value value) {
      if (int32ValueBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        int32Value_ = value;
        onChanged();
      } else {
        int32ValueBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int32Value int32_value = 2;</code>
     */
    public Builder setInt32Value(
        com.google.protobuf.Int32Value.Builder builderForValue) {
      if (int32ValueBuilder_ == null) {
        int32Value_ = builderForValue.build();
        onChanged();
      } else {
        int32ValueBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int32Value int32_value = 2;</code>
     */
    public Builder mergeInt32Value(com.google.protobuf.Int32Value value) {
      if (int32ValueBuilder_ == null) {
        if (int32Value_ != null) {
          int32Value_ =
            com.google.protobuf.Int32Value.newBuilder(int32Value_).mergeFrom(value).buildPartial();
        } else {
          int32Value_ = value;
        }
        onChanged();
      } else {
        int32ValueBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int32Value int32_value = 2;</code>
     */
    public Builder clearInt32Value() {
      if (int32ValueBuilder_ == null) {
        int32Value_ = null;
        onChanged();
      } else {
        int32Value_ = null;
        int32ValueBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int32Value int32_value = 2;</code>
     */
    public com.google.protobuf.Int32Value.Builder getInt32ValueBuilder() {
      
      onChanged();
      return getInt32ValueFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Int32Value int32_value = 2;</code>
     */
    public com.google.protobuf.Int32ValueOrBuilder getInt32ValueOrBuilder() {
      if (int32ValueBuilder_ != null) {
        return int32ValueBuilder_.getMessageOrBuilder();
      } else {
        return int32Value_ == null ?
            com.google.protobuf.Int32Value.getDefaultInstance() : int32Value_;
      }
    }
    /**
     * <code>.google.protobuf.Int32Value int32_value = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder> 
        getInt32ValueFieldBuilder() {
      if (int32ValueBuilder_ == null) {
        int32ValueBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder>(
                getInt32Value(),
                getParentForChildren(),
                isClean());
        int32Value_ = null;
      }
      return int32ValueBuilder_;
    }

    private uk.me.uohiro.protobuf.model.ch10.ex3.FieldMaskRequest.NestedMessage nestedMessage_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        uk.me.uohiro.protobuf.model.ch10.ex3.FieldMaskRequest.NestedMessage, uk.me.uohiro.protobuf.model.ch10.ex3.FieldMaskRequest.NestedMessage.Builder, uk.me.uohiro.protobuf.model.ch10.ex3.FieldMaskRequest.NestedMessageOrBuilder> nestedMessageBuilder_;
    /**
     * <code>.ch10.ex3.FieldMaskRequest.NestedMessage nested_message = 3;</code>
     */
    public boolean hasNestedMessage() {
      return nestedMessageBuilder_ != null || nestedMessage_ != null;
    }
    /**
     * <code>.ch10.ex3.FieldMaskRequest.NestedMessage nested_message = 3;</code>
     */
    public uk.me.uohiro.protobuf.model.ch10.ex3.FieldMaskRequest.NestedMessage getNestedMessage() {
      if (nestedMessageBuilder_ == null) {
        return nestedMessage_ == null ? uk.me.uohiro.protobuf.model.ch10.ex3.FieldMaskRequest.NestedMessage.getDefaultInstance() : nestedMessage_;
      } else {
        return nestedMessageBuilder_.getMessage();
      }
    }
    /**
     * <code>.ch10.ex3.FieldMaskRequest.NestedMessage nested_message = 3;</code>
     */
    public Builder setNestedMessage(uk.me.uohiro.protobuf.model.ch10.ex3.FieldMaskRequest.NestedMessage value) {
      if (nestedMessageBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        nestedMessage_ = value;
        onChanged();
      } else {
        nestedMessageBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.ch10.ex3.FieldMaskRequest.NestedMessage nested_message = 3;</code>
     */
    public Builder setNestedMessage(
        uk.me.uohiro.protobuf.model.ch10.ex3.FieldMaskRequest.NestedMessage.Builder builderForValue) {
      if (nestedMessageBuilder_ == null) {
        nestedMessage_ = builderForValue.build();
        onChanged();
      } else {
        nestedMessageBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.ch10.ex3.FieldMaskRequest.NestedMessage nested_message = 3;</code>
     */
    public Builder mergeNestedMessage(uk.me.uohiro.protobuf.model.ch10.ex3.FieldMaskRequest.NestedMessage value) {
      if (nestedMessageBuilder_ == null) {
        if (nestedMessage_ != null) {
          nestedMessage_ =
            uk.me.uohiro.protobuf.model.ch10.ex3.FieldMaskRequest.NestedMessage.newBuilder(nestedMessage_).mergeFrom(value).buildPartial();
        } else {
          nestedMessage_ = value;
        }
        onChanged();
      } else {
        nestedMessageBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.ch10.ex3.FieldMaskRequest.NestedMessage nested_message = 3;</code>
     */
    public Builder clearNestedMessage() {
      if (nestedMessageBuilder_ == null) {
        nestedMessage_ = null;
        onChanged();
      } else {
        nestedMessage_ = null;
        nestedMessageBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.ch10.ex3.FieldMaskRequest.NestedMessage nested_message = 3;</code>
     */
    public uk.me.uohiro.protobuf.model.ch10.ex3.FieldMaskRequest.NestedMessage.Builder getNestedMessageBuilder() {
      
      onChanged();
      return getNestedMessageFieldBuilder().getBuilder();
    }
    /**
     * <code>.ch10.ex3.FieldMaskRequest.NestedMessage nested_message = 3;</code>
     */
    public uk.me.uohiro.protobuf.model.ch10.ex3.FieldMaskRequest.NestedMessageOrBuilder getNestedMessageOrBuilder() {
      if (nestedMessageBuilder_ != null) {
        return nestedMessageBuilder_.getMessageOrBuilder();
      } else {
        return nestedMessage_ == null ?
            uk.me.uohiro.protobuf.model.ch10.ex3.FieldMaskRequest.NestedMessage.getDefaultInstance() : nestedMessage_;
      }
    }
    /**
     * <code>.ch10.ex3.FieldMaskRequest.NestedMessage nested_message = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        uk.me.uohiro.protobuf.model.ch10.ex3.FieldMaskRequest.NestedMessage, uk.me.uohiro.protobuf.model.ch10.ex3.FieldMaskRequest.NestedMessage.Builder, uk.me.uohiro.protobuf.model.ch10.ex3.FieldMaskRequest.NestedMessageOrBuilder> 
        getNestedMessageFieldBuilder() {
      if (nestedMessageBuilder_ == null) {
        nestedMessageBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            uk.me.uohiro.protobuf.model.ch10.ex3.FieldMaskRequest.NestedMessage, uk.me.uohiro.protobuf.model.ch10.ex3.FieldMaskRequest.NestedMessage.Builder, uk.me.uohiro.protobuf.model.ch10.ex3.FieldMaskRequest.NestedMessageOrBuilder>(
                getNestedMessage(),
                getParentForChildren(),
                isClean());
        nestedMessage_ = null;
      }
      return nestedMessageBuilder_;
    }

    private com.google.protobuf.FieldMask mask_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.FieldMask, com.google.protobuf.FieldMask.Builder, com.google.protobuf.FieldMaskOrBuilder> maskBuilder_;
    /**
     * <code>.google.protobuf.FieldMask mask = 4;</code>
     */
    public boolean hasMask() {
      return maskBuilder_ != null || mask_ != null;
    }
    /**
     * <code>.google.protobuf.FieldMask mask = 4;</code>
     */
    public com.google.protobuf.FieldMask getMask() {
      if (maskBuilder_ == null) {
        return mask_ == null ? com.google.protobuf.FieldMask.getDefaultInstance() : mask_;
      } else {
        return maskBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.FieldMask mask = 4;</code>
     */
    public Builder setMask(com.google.protobuf.FieldMask value) {
      if (maskBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        mask_ = value;
        onChanged();
      } else {
        maskBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.FieldMask mask = 4;</code>
     */
    public Builder setMask(
        com.google.protobuf.FieldMask.Builder builderForValue) {
      if (maskBuilder_ == null) {
        mask_ = builderForValue.build();
        onChanged();
      } else {
        maskBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.FieldMask mask = 4;</code>
     */
    public Builder mergeMask(com.google.protobuf.FieldMask value) {
      if (maskBuilder_ == null) {
        if (mask_ != null) {
          mask_ =
            com.google.protobuf.FieldMask.newBuilder(mask_).mergeFrom(value).buildPartial();
        } else {
          mask_ = value;
        }
        onChanged();
      } else {
        maskBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.FieldMask mask = 4;</code>
     */
    public Builder clearMask() {
      if (maskBuilder_ == null) {
        mask_ = null;
        onChanged();
      } else {
        mask_ = null;
        maskBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.FieldMask mask = 4;</code>
     */
    public com.google.protobuf.FieldMask.Builder getMaskBuilder() {
      
      onChanged();
      return getMaskFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.FieldMask mask = 4;</code>
     */
    public com.google.protobuf.FieldMaskOrBuilder getMaskOrBuilder() {
      if (maskBuilder_ != null) {
        return maskBuilder_.getMessageOrBuilder();
      } else {
        return mask_ == null ?
            com.google.protobuf.FieldMask.getDefaultInstance() : mask_;
      }
    }
    /**
     * <code>.google.protobuf.FieldMask mask = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.FieldMask, com.google.protobuf.FieldMask.Builder, com.google.protobuf.FieldMaskOrBuilder> 
        getMaskFieldBuilder() {
      if (maskBuilder_ == null) {
        maskBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.FieldMask, com.google.protobuf.FieldMask.Builder, com.google.protobuf.FieldMaskOrBuilder>(
                getMask(),
                getParentForChildren(),
                isClean());
        mask_ = null;
      }
      return maskBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ch10.ex3.FieldMaskRequest)
  }

  // @@protoc_insertion_point(class_scope:ch10.ex3.FieldMaskRequest)
  private static final uk.me.uohiro.protobuf.model.ch10.ex3.FieldMaskRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new uk.me.uohiro.protobuf.model.ch10.ex3.FieldMaskRequest();
  }

  public static uk.me.uohiro.protobuf.model.ch10.ex3.FieldMaskRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FieldMaskRequest>
      PARSER = new com.google.protobuf.AbstractParser<FieldMaskRequest>() {
    @java.lang.Override
    public FieldMaskRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new FieldMaskRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<FieldMaskRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FieldMaskRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public uk.me.uohiro.protobuf.model.ch10.ex3.FieldMaskRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

