// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ch4/sfapi.proto

package uk.me.uohiro.protobuf.model.ch4;

public interface FilmOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ch4.Film)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string title = 2;</code>
   */
  java.lang.String getTitle();
  /**
   * <code>string title = 2;</code>
   */
  com.google.protobuf.ByteString
      getTitleBytes();

  /**
   * <code>string director = 3;</code>
   */
  java.lang.String getDirector();
  /**
   * <code>string director = 3;</code>
   */
  com.google.protobuf.ByteString
      getDirectorBytes();

  /**
   * <code>string producer = 4;</code>
   */
  java.lang.String getProducer();
  /**
   * <code>string producer = 4;</code>
   */
  com.google.protobuf.ByteString
      getProducerBytes();

  /**
   * <code>.google.protobuf.Timestamp release_date = 5;</code>
   */
  boolean hasReleaseDate();
  /**
   * <code>.google.protobuf.Timestamp release_date = 5;</code>
   */
  com.google.protobuf.Timestamp getReleaseDate();
  /**
   * <code>.google.protobuf.Timestamp release_date = 5;</code>
   */
  com.google.protobuf.TimestampOrBuilder getReleaseDateOrBuilder();
}
