// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ch4/sfapi.proto

package uk.me.uohiro.protobuf.model.ch4;

/**
 * Protobuf type {@code ch4.GetFilmResponse}
 */
public  final class GetFilmResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ch4.GetFilmResponse)
    GetFilmResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetFilmResponse.newBuilder() to construct.
  private GetFilmResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetFilmResponse() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GetFilmResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            uk.me.uohiro.protobuf.model.ch4.Film.Builder subBuilder = null;
            if (film_ != null) {
              subBuilder = film_.toBuilder();
            }
            film_ = input.readMessage(uk.me.uohiro.protobuf.model.ch4.Film.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(film_);
              film_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return uk.me.uohiro.protobuf.model.ch4.StarFriendsAPIProto.internal_static_ch4_GetFilmResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return uk.me.uohiro.protobuf.model.ch4.StarFriendsAPIProto.internal_static_ch4_GetFilmResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            uk.me.uohiro.protobuf.model.ch4.GetFilmResponse.class, uk.me.uohiro.protobuf.model.ch4.GetFilmResponse.Builder.class);
  }

  public static final int FILM_FIELD_NUMBER = 1;
  private uk.me.uohiro.protobuf.model.ch4.Film film_;
  /**
   * <code>.ch4.Film film = 1;</code>
   */
  public boolean hasFilm() {
    return film_ != null;
  }
  /**
   * <code>.ch4.Film film = 1;</code>
   */
  public uk.me.uohiro.protobuf.model.ch4.Film getFilm() {
    return film_ == null ? uk.me.uohiro.protobuf.model.ch4.Film.getDefaultInstance() : film_;
  }
  /**
   * <code>.ch4.Film film = 1;</code>
   */
  public uk.me.uohiro.protobuf.model.ch4.FilmOrBuilder getFilmOrBuilder() {
    return getFilm();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (film_ != null) {
      output.writeMessage(1, getFilm());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (film_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getFilm());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof uk.me.uohiro.protobuf.model.ch4.GetFilmResponse)) {
      return super.equals(obj);
    }
    uk.me.uohiro.protobuf.model.ch4.GetFilmResponse other = (uk.me.uohiro.protobuf.model.ch4.GetFilmResponse) obj;

    boolean result = true;
    result = result && (hasFilm() == other.hasFilm());
    if (hasFilm()) {
      result = result && getFilm()
          .equals(other.getFilm());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasFilm()) {
      hash = (37 * hash) + FILM_FIELD_NUMBER;
      hash = (53 * hash) + getFilm().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static uk.me.uohiro.protobuf.model.ch4.GetFilmResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static uk.me.uohiro.protobuf.model.ch4.GetFilmResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static uk.me.uohiro.protobuf.model.ch4.GetFilmResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static uk.me.uohiro.protobuf.model.ch4.GetFilmResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static uk.me.uohiro.protobuf.model.ch4.GetFilmResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static uk.me.uohiro.protobuf.model.ch4.GetFilmResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static uk.me.uohiro.protobuf.model.ch4.GetFilmResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static uk.me.uohiro.protobuf.model.ch4.GetFilmResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static uk.me.uohiro.protobuf.model.ch4.GetFilmResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static uk.me.uohiro.protobuf.model.ch4.GetFilmResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static uk.me.uohiro.protobuf.model.ch4.GetFilmResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static uk.me.uohiro.protobuf.model.ch4.GetFilmResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(uk.me.uohiro.protobuf.model.ch4.GetFilmResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ch4.GetFilmResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ch4.GetFilmResponse)
      uk.me.uohiro.protobuf.model.ch4.GetFilmResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return uk.me.uohiro.protobuf.model.ch4.StarFriendsAPIProto.internal_static_ch4_GetFilmResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return uk.me.uohiro.protobuf.model.ch4.StarFriendsAPIProto.internal_static_ch4_GetFilmResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              uk.me.uohiro.protobuf.model.ch4.GetFilmResponse.class, uk.me.uohiro.protobuf.model.ch4.GetFilmResponse.Builder.class);
    }

    // Construct using uk.me.uohiro.protobuf.model.ch4.GetFilmResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (filmBuilder_ == null) {
        film_ = null;
      } else {
        film_ = null;
        filmBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return uk.me.uohiro.protobuf.model.ch4.StarFriendsAPIProto.internal_static_ch4_GetFilmResponse_descriptor;
    }

    @java.lang.Override
    public uk.me.uohiro.protobuf.model.ch4.GetFilmResponse getDefaultInstanceForType() {
      return uk.me.uohiro.protobuf.model.ch4.GetFilmResponse.getDefaultInstance();
    }

    @java.lang.Override
    public uk.me.uohiro.protobuf.model.ch4.GetFilmResponse build() {
      uk.me.uohiro.protobuf.model.ch4.GetFilmResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public uk.me.uohiro.protobuf.model.ch4.GetFilmResponse buildPartial() {
      uk.me.uohiro.protobuf.model.ch4.GetFilmResponse result = new uk.me.uohiro.protobuf.model.ch4.GetFilmResponse(this);
      if (filmBuilder_ == null) {
        result.film_ = film_;
      } else {
        result.film_ = filmBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof uk.me.uohiro.protobuf.model.ch4.GetFilmResponse) {
        return mergeFrom((uk.me.uohiro.protobuf.model.ch4.GetFilmResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(uk.me.uohiro.protobuf.model.ch4.GetFilmResponse other) {
      if (other == uk.me.uohiro.protobuf.model.ch4.GetFilmResponse.getDefaultInstance()) return this;
      if (other.hasFilm()) {
        mergeFilm(other.getFilm());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      uk.me.uohiro.protobuf.model.ch4.GetFilmResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (uk.me.uohiro.protobuf.model.ch4.GetFilmResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private uk.me.uohiro.protobuf.model.ch4.Film film_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        uk.me.uohiro.protobuf.model.ch4.Film, uk.me.uohiro.protobuf.model.ch4.Film.Builder, uk.me.uohiro.protobuf.model.ch4.FilmOrBuilder> filmBuilder_;
    /**
     * <code>.ch4.Film film = 1;</code>
     */
    public boolean hasFilm() {
      return filmBuilder_ != null || film_ != null;
    }
    /**
     * <code>.ch4.Film film = 1;</code>
     */
    public uk.me.uohiro.protobuf.model.ch4.Film getFilm() {
      if (filmBuilder_ == null) {
        return film_ == null ? uk.me.uohiro.protobuf.model.ch4.Film.getDefaultInstance() : film_;
      } else {
        return filmBuilder_.getMessage();
      }
    }
    /**
     * <code>.ch4.Film film = 1;</code>
     */
    public Builder setFilm(uk.me.uohiro.protobuf.model.ch4.Film value) {
      if (filmBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        film_ = value;
        onChanged();
      } else {
        filmBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.ch4.Film film = 1;</code>
     */
    public Builder setFilm(
        uk.me.uohiro.protobuf.model.ch4.Film.Builder builderForValue) {
      if (filmBuilder_ == null) {
        film_ = builderForValue.build();
        onChanged();
      } else {
        filmBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.ch4.Film film = 1;</code>
     */
    public Builder mergeFilm(uk.me.uohiro.protobuf.model.ch4.Film value) {
      if (filmBuilder_ == null) {
        if (film_ != null) {
          film_ =
            uk.me.uohiro.protobuf.model.ch4.Film.newBuilder(film_).mergeFrom(value).buildPartial();
        } else {
          film_ = value;
        }
        onChanged();
      } else {
        filmBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.ch4.Film film = 1;</code>
     */
    public Builder clearFilm() {
      if (filmBuilder_ == null) {
        film_ = null;
        onChanged();
      } else {
        film_ = null;
        filmBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.ch4.Film film = 1;</code>
     */
    public uk.me.uohiro.protobuf.model.ch4.Film.Builder getFilmBuilder() {
      
      onChanged();
      return getFilmFieldBuilder().getBuilder();
    }
    /**
     * <code>.ch4.Film film = 1;</code>
     */
    public uk.me.uohiro.protobuf.model.ch4.FilmOrBuilder getFilmOrBuilder() {
      if (filmBuilder_ != null) {
        return filmBuilder_.getMessageOrBuilder();
      } else {
        return film_ == null ?
            uk.me.uohiro.protobuf.model.ch4.Film.getDefaultInstance() : film_;
      }
    }
    /**
     * <code>.ch4.Film film = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        uk.me.uohiro.protobuf.model.ch4.Film, uk.me.uohiro.protobuf.model.ch4.Film.Builder, uk.me.uohiro.protobuf.model.ch4.FilmOrBuilder> 
        getFilmFieldBuilder() {
      if (filmBuilder_ == null) {
        filmBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            uk.me.uohiro.protobuf.model.ch4.Film, uk.me.uohiro.protobuf.model.ch4.Film.Builder, uk.me.uohiro.protobuf.model.ch4.FilmOrBuilder>(
                getFilm(),
                getParentForChildren(),
                isClean());
        film_ = null;
      }
      return filmBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ch4.GetFilmResponse)
  }

  // @@protoc_insertion_point(class_scope:ch4.GetFilmResponse)
  private static final uk.me.uohiro.protobuf.model.ch4.GetFilmResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new uk.me.uohiro.protobuf.model.ch4.GetFilmResponse();
  }

  public static uk.me.uohiro.protobuf.model.ch4.GetFilmResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetFilmResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetFilmResponse>() {
    @java.lang.Override
    public GetFilmResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GetFilmResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetFilmResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetFilmResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public uk.me.uohiro.protobuf.model.ch4.GetFilmResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

