// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ch4/sfapi.proto

package uk.me.uohiro.protobuf.model.ch4;

public interface GetFilmResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ch4.GetFilmResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.ch4.Film film = 1;</code>
   */
  boolean hasFilm();
  /**
   * <code>.ch4.Film film = 1;</code>
   */
  uk.me.uohiro.protobuf.model.ch4.Film getFilm();
  /**
   * <code>.ch4.Film film = 1;</code>
   */
  uk.me.uohiro.protobuf.model.ch4.FilmOrBuilder getFilmOrBuilder();
}
