// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ch7/error-mgmt.proto

package uk.me.uohiro.protobuf.model.ch7.ex1;

public interface GetDataResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ch7.ex1.GetDataResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string data = 2;</code>
   */
  java.lang.String getData();
  /**
   * <code>string data = 2;</code>
   */
  com.google.protobuf.ByteString
      getDataBytes();
}
