// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ch6/archiver.proto

package uk.me.uohiro.protobuf.model.ch6.ex2;

public final class ArchiverServiceProto {
  private ArchiverServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ch6_ex2_ZipRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ch6_ex2_ZipRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ch6_ex2_ZipResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ch6_ex2_ZipResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022ch6/archiver.proto\022\007ch6.ex2\"1\n\nZipRequ" +
      "est\022\021\n\tfile_name\030\001 \001(\t\022\020\n\010contents\030\002 \001(\014" +
      "\"&\n\013ZipResponse\022\027\n\017zipped_contents\030\001 \001(\014" +
      "2>\n\010Archiver\0222\n\003Zip\022\023.ch6.ex2.ZipRequest" +
      "\032\024.ch6.ex2.ZipResponse(\001B?\n#uk.me.uohiro" +
      ".protobuf.model.ch6.ex2B\024ArchiverService" +
      "ProtoH\001P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ch6_ex2_ZipRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ch6_ex2_ZipRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ch6_ex2_ZipRequest_descriptor,
        new java.lang.String[] { "FileName", "Contents", });
    internal_static_ch6_ex2_ZipResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ch6_ex2_ZipResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ch6_ex2_ZipResponse_descriptor,
        new java.lang.String[] { "ZippedContents", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
