// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ch10/ex1/version.proto

package uk.me.uohiro.protobuf.model.ch10.ex1.v1;

public interface NameOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ch10.ex1.Name)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string first_name = 1;</code>
   */
  java.lang.String getFirstName();
  /**
   * <code>string first_name = 1;</code>
   */
  com.google.protobuf.ByteString
      getFirstNameBytes();
}
