// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ch3/ex10.proto

package uk.me.uohiro.protobuf.model.ch3.ex10;

public interface CharacterOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ch3.ex10.Character)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int64 birth = 2;</code>
   */
  long getBirth();

  /**
   * <code>string laser_gun_model = 3;</code>
   */
  java.lang.String getLaserGunModel();
  /**
   * <code>string laser_gun_model = 3;</code>
   */
  com.google.protobuf.ByteString
      getLaserGunModelBytes();

  /**
   * <code>int32 laser_sword_power = 4;</code>
   */
  int getLaserSwordPower();

  public uk.me.uohiro.protobuf.model.ch3.ex10.Character.HasCase getHasCase();
}
