// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ch3/ex10.proto

package uk.me.uohiro.protobuf.model.ch3.ex10;

public final class FilmProto {
  private FilmProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ch3_ex10_Character_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ch3_ex10_Character_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ch3_ex10_Film_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ch3_ex10_Film_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ch3_ex10_Film_RolesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ch3_ex10_Film_RolesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ch3_ex10_TerrorFilm_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ch3_ex10_TerrorFilm_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ch3_ex10_ScienceFictionFilm_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ch3_ex10_ScienceFictionFilm_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016ch3/ex10.proto\022\010ch3.ex10\032\031google/proto" +
      "buf/any.proto\"g\n\tCharacter\022\014\n\004name\030\001 \001(\t" +
      "\022\r\n\005birth\030\002 \001(\003\022\031\n\017laser_gun_model\030\003 \001(\t" +
      "H\000\022\033\n\021laser_sword_power\030\004 \001(\005H\000B\005\n\003has\"\236" +
      "\002\n\004Film\022\r\n\005title\030\001 \001(\t\022\020\n\010director\030\002 \001(\t" +
      "\022\020\n\010producer\030\003 \001(\t\022\024\n\014release_date\030\004 \001(\t" +
      "\022(\n\005roles\030\005 \003(\0132\031.ch3.ex10.Film.RolesEnt" +
      "ry\0225\n\020producer_company\030\006 \001(\0162\033.ch3.ex10." +
      "ProducerCompanies\022)\n\013film_detail\030\007 \001(\0132\024" +
      ".google.protobuf.Any\032A\n\nRolesEntry\022\013\n\003ke" +
      "y\030\001 \001(\t\022\"\n\005value\030\002 \001(\0132\023.ch3.ex10.Charac" +
      "ter:\0028\001\"!\n\nTerrorFilm\022\023\n\013has_zombies\030\001 \001" +
      "(\010\"\'\n\022ScienceFictionFilm\022\021\n\thas_jedis\030\001 " +
      "\001(\010*M\n\021ProducerCompanies\022\013\n\007UNKNOWN\020\000\022\017\n" +
      "\013WARNER_BROS\020\001\022\r\n\tPARAMOUNT\020\002\022\013\n\007NETFLIX" +
      "\020\003B5\n$uk.me.uohiro.protobuf.model.ch3.ex" +
      "10B\tFilmProtoH\001P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
        }, assigner);
    internal_static_ch3_ex10_Character_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ch3_ex10_Character_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ch3_ex10_Character_descriptor,
        new java.lang.String[] { "Name", "Birth", "LaserGunModel", "LaserSwordPower", "Has", });
    internal_static_ch3_ex10_Film_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ch3_ex10_Film_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ch3_ex10_Film_descriptor,
        new java.lang.String[] { "Title", "Director", "Producer", "ReleaseDate", "Roles", "ProducerCompany", "FilmDetail", });
    internal_static_ch3_ex10_Film_RolesEntry_descriptor =
      internal_static_ch3_ex10_Film_descriptor.getNestedTypes().get(0);
    internal_static_ch3_ex10_Film_RolesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ch3_ex10_Film_RolesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_ch3_ex10_TerrorFilm_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ch3_ex10_TerrorFilm_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ch3_ex10_TerrorFilm_descriptor,
        new java.lang.String[] { "HasZombies", });
    internal_static_ch3_ex10_ScienceFictionFilm_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_ch3_ex10_ScienceFictionFilm_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ch3_ex10_ScienceFictionFilm_descriptor,
        new java.lang.String[] { "HasJedis", });
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
