// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ch3/ex10.proto

package uk.me.uohiro.protobuf.model.ch3.ex10;

public interface ScienceFictionFilmOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ch3.ex10.ScienceFictionFilm)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool has_jedis = 1;</code>
   */
  boolean getHasJedis();
}
