// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ch3/ex11.proto

package uk.me.uohiro.protobuf.model.ch3.ex11;

public interface ScienceFictionFilmOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ch3.ex11.ScienceFictionFilm)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional bool has_jedis = 1;</code>
   */
  boolean hasHasJedis();
  /**
   * <code>optional bool has_jedis = 1;</code>
   */
  boolean getHasJedis();
}
