// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ch3/ex1.proto

package uk.me.uohiro.protobuf.model.ch3.ex1;

/**
 * Protobuf type {@code ch3.ex1.Film}
 */
public  final class Film extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ch3.ex1.Film)
    FilmOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Film.newBuilder() to construct.
  private Film(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Film() {
    title_ = "";
    director_ = "";
    producer_ = "";
    releaseDate_ = "";
    character_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Film(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000001;
            title_ = bs;
            break;
          }
          case 18: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000002;
            director_ = bs;
            break;
          }
          case 26: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000004;
            producer_ = bs;
            break;
          }
          case 34: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000008;
            releaseDate_ = bs;
            break;
          }
          case 42: {
            com.google.protobuf.ByteString bs = input.readBytes();
            if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
              character_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000010;
            }
            character_.add(bs);
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
        character_ = character_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return uk.me.uohiro.protobuf.model.ch3.ex1.FilmProto.internal_static_ch3_ex1_Film_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return uk.me.uohiro.protobuf.model.ch3.ex1.FilmProto.internal_static_ch3_ex1_Film_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            uk.me.uohiro.protobuf.model.ch3.ex1.Film.class, uk.me.uohiro.protobuf.model.ch3.ex1.Film.Builder.class);
  }

  private int bitField0_;
  public static final int TITLE_FIELD_NUMBER = 1;
  private volatile java.lang.Object title_;
  /**
   * <code>required string title = 1;</code>
   */
  public boolean hasTitle() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>required string title = 1;</code>
   */
  public java.lang.String getTitle() {
    java.lang.Object ref = title_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        title_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string title = 1;</code>
   */
  public com.google.protobuf.ByteString
      getTitleBytes() {
    java.lang.Object ref = title_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      title_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DIRECTOR_FIELD_NUMBER = 2;
  private volatile java.lang.Object director_;
  /**
   * <code>required string director = 2;</code>
   */
  public boolean hasDirector() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>required string director = 2;</code>
   */
  public java.lang.String getDirector() {
    java.lang.Object ref = director_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        director_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string director = 2;</code>
   */
  public com.google.protobuf.ByteString
      getDirectorBytes() {
    java.lang.Object ref = director_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      director_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PRODUCER_FIELD_NUMBER = 3;
  private volatile java.lang.Object producer_;
  /**
   * <code>required string producer = 3;</code>
   */
  public boolean hasProducer() {
    return ((bitField0_ & 0x00000004) == 0x00000004);
  }
  /**
   * <code>required string producer = 3;</code>
   */
  public java.lang.String getProducer() {
    java.lang.Object ref = producer_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        producer_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string producer = 3;</code>
   */
  public com.google.protobuf.ByteString
      getProducerBytes() {
    java.lang.Object ref = producer_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      producer_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RELEASE_DATE_FIELD_NUMBER = 4;
  private volatile java.lang.Object releaseDate_;
  /**
   * <code>optional string release_date = 4;</code>
   */
  public boolean hasReleaseDate() {
    return ((bitField0_ & 0x00000008) == 0x00000008);
  }
  /**
   * <code>optional string release_date = 4;</code>
   */
  public java.lang.String getReleaseDate() {
    java.lang.Object ref = releaseDate_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        releaseDate_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string release_date = 4;</code>
   */
  public com.google.protobuf.ByteString
      getReleaseDateBytes() {
    java.lang.Object ref = releaseDate_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      releaseDate_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CHARACTER_FIELD_NUMBER = 5;
  private com.google.protobuf.LazyStringList character_;
  /**
   * <code>repeated string character = 5;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getCharacterList() {
    return character_;
  }
  /**
   * <code>repeated string character = 5;</code>
   */
  public int getCharacterCount() {
    return character_.size();
  }
  /**
   * <code>repeated string character = 5;</code>
   */
  public java.lang.String getCharacter(int index) {
    return character_.get(index);
  }
  /**
   * <code>repeated string character = 5;</code>
   */
  public com.google.protobuf.ByteString
      getCharacterBytes(int index) {
    return character_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasTitle()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasDirector()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasProducer()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, title_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, director_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, producer_);
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, releaseDate_);
    }
    for (int i = 0; i < character_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, character_.getRaw(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, title_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, director_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, producer_);
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, releaseDate_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < character_.size(); i++) {
        dataSize += computeStringSizeNoTag(character_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getCharacterList().size();
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof uk.me.uohiro.protobuf.model.ch3.ex1.Film)) {
      return super.equals(obj);
    }
    uk.me.uohiro.protobuf.model.ch3.ex1.Film other = (uk.me.uohiro.protobuf.model.ch3.ex1.Film) obj;

    boolean result = true;
    result = result && (hasTitle() == other.hasTitle());
    if (hasTitle()) {
      result = result && getTitle()
          .equals(other.getTitle());
    }
    result = result && (hasDirector() == other.hasDirector());
    if (hasDirector()) {
      result = result && getDirector()
          .equals(other.getDirector());
    }
    result = result && (hasProducer() == other.hasProducer());
    if (hasProducer()) {
      result = result && getProducer()
          .equals(other.getProducer());
    }
    result = result && (hasReleaseDate() == other.hasReleaseDate());
    if (hasReleaseDate()) {
      result = result && getReleaseDate()
          .equals(other.getReleaseDate());
    }
    result = result && getCharacterList()
        .equals(other.getCharacterList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasTitle()) {
      hash = (37 * hash) + TITLE_FIELD_NUMBER;
      hash = (53 * hash) + getTitle().hashCode();
    }
    if (hasDirector()) {
      hash = (37 * hash) + DIRECTOR_FIELD_NUMBER;
      hash = (53 * hash) + getDirector().hashCode();
    }
    if (hasProducer()) {
      hash = (37 * hash) + PRODUCER_FIELD_NUMBER;
      hash = (53 * hash) + getProducer().hashCode();
    }
    if (hasReleaseDate()) {
      hash = (37 * hash) + RELEASE_DATE_FIELD_NUMBER;
      hash = (53 * hash) + getReleaseDate().hashCode();
    }
    if (getCharacterCount() > 0) {
      hash = (37 * hash) + CHARACTER_FIELD_NUMBER;
      hash = (53 * hash) + getCharacterList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static uk.me.uohiro.protobuf.model.ch3.ex1.Film parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static uk.me.uohiro.protobuf.model.ch3.ex1.Film parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static uk.me.uohiro.protobuf.model.ch3.ex1.Film parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static uk.me.uohiro.protobuf.model.ch3.ex1.Film parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static uk.me.uohiro.protobuf.model.ch3.ex1.Film parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static uk.me.uohiro.protobuf.model.ch3.ex1.Film parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static uk.me.uohiro.protobuf.model.ch3.ex1.Film parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static uk.me.uohiro.protobuf.model.ch3.ex1.Film parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static uk.me.uohiro.protobuf.model.ch3.ex1.Film parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static uk.me.uohiro.protobuf.model.ch3.ex1.Film parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static uk.me.uohiro.protobuf.model.ch3.ex1.Film parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static uk.me.uohiro.protobuf.model.ch3.ex1.Film parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(uk.me.uohiro.protobuf.model.ch3.ex1.Film prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ch3.ex1.Film}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ch3.ex1.Film)
      uk.me.uohiro.protobuf.model.ch3.ex1.FilmOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return uk.me.uohiro.protobuf.model.ch3.ex1.FilmProto.internal_static_ch3_ex1_Film_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return uk.me.uohiro.protobuf.model.ch3.ex1.FilmProto.internal_static_ch3_ex1_Film_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              uk.me.uohiro.protobuf.model.ch3.ex1.Film.class, uk.me.uohiro.protobuf.model.ch3.ex1.Film.Builder.class);
    }

    // Construct using uk.me.uohiro.protobuf.model.ch3.ex1.Film.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      title_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      director_ = "";
      bitField0_ = (bitField0_ & ~0x00000002);
      producer_ = "";
      bitField0_ = (bitField0_ & ~0x00000004);
      releaseDate_ = "";
      bitField0_ = (bitField0_ & ~0x00000008);
      character_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000010);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return uk.me.uohiro.protobuf.model.ch3.ex1.FilmProto.internal_static_ch3_ex1_Film_descriptor;
    }

    @java.lang.Override
    public uk.me.uohiro.protobuf.model.ch3.ex1.Film getDefaultInstanceForType() {
      return uk.me.uohiro.protobuf.model.ch3.ex1.Film.getDefaultInstance();
    }

    @java.lang.Override
    public uk.me.uohiro.protobuf.model.ch3.ex1.Film build() {
      uk.me.uohiro.protobuf.model.ch3.ex1.Film result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public uk.me.uohiro.protobuf.model.ch3.ex1.Film buildPartial() {
      uk.me.uohiro.protobuf.model.ch3.ex1.Film result = new uk.me.uohiro.protobuf.model.ch3.ex1.Film(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.title_ = title_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      result.director_ = director_;
      if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
        to_bitField0_ |= 0x00000004;
      }
      result.producer_ = producer_;
      if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
        to_bitField0_ |= 0x00000008;
      }
      result.releaseDate_ = releaseDate_;
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        character_ = character_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000010);
      }
      result.character_ = character_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof uk.me.uohiro.protobuf.model.ch3.ex1.Film) {
        return mergeFrom((uk.me.uohiro.protobuf.model.ch3.ex1.Film)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(uk.me.uohiro.protobuf.model.ch3.ex1.Film other) {
      if (other == uk.me.uohiro.protobuf.model.ch3.ex1.Film.getDefaultInstance()) return this;
      if (other.hasTitle()) {
        bitField0_ |= 0x00000001;
        title_ = other.title_;
        onChanged();
      }
      if (other.hasDirector()) {
        bitField0_ |= 0x00000002;
        director_ = other.director_;
        onChanged();
      }
      if (other.hasProducer()) {
        bitField0_ |= 0x00000004;
        producer_ = other.producer_;
        onChanged();
      }
      if (other.hasReleaseDate()) {
        bitField0_ |= 0x00000008;
        releaseDate_ = other.releaseDate_;
        onChanged();
      }
      if (!other.character_.isEmpty()) {
        if (character_.isEmpty()) {
          character_ = other.character_;
          bitField0_ = (bitField0_ & ~0x00000010);
        } else {
          ensureCharacterIsMutable();
          character_.addAll(other.character_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      if (!hasTitle()) {
        return false;
      }
      if (!hasDirector()) {
        return false;
      }
      if (!hasProducer()) {
        return false;
      }
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      uk.me.uohiro.protobuf.model.ch3.ex1.Film parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (uk.me.uohiro.protobuf.model.ch3.ex1.Film) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object title_ = "";
    /**
     * <code>required string title = 1;</code>
     */
    public boolean hasTitle() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string title = 1;</code>
     */
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          title_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>required string title = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string title = 1;</code>
     */
    public Builder setTitle(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      title_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required string title = 1;</code>
     */
    public Builder clearTitle() {
      bitField0_ = (bitField0_ & ~0x00000001);
      title_ = getDefaultInstance().getTitle();
      onChanged();
      return this;
    }
    /**
     * <code>required string title = 1;</code>
     */
    public Builder setTitleBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      title_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object director_ = "";
    /**
     * <code>required string director = 2;</code>
     */
    public boolean hasDirector() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string director = 2;</code>
     */
    public java.lang.String getDirector() {
      java.lang.Object ref = director_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          director_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>required string director = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDirectorBytes() {
      java.lang.Object ref = director_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        director_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string director = 2;</code>
     */
    public Builder setDirector(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      director_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required string director = 2;</code>
     */
    public Builder clearDirector() {
      bitField0_ = (bitField0_ & ~0x00000002);
      director_ = getDefaultInstance().getDirector();
      onChanged();
      return this;
    }
    /**
     * <code>required string director = 2;</code>
     */
    public Builder setDirectorBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      director_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object producer_ = "";
    /**
     * <code>required string producer = 3;</code>
     */
    public boolean hasProducer() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string producer = 3;</code>
     */
    public java.lang.String getProducer() {
      java.lang.Object ref = producer_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          producer_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>required string producer = 3;</code>
     */
    public com.google.protobuf.ByteString
        getProducerBytes() {
      java.lang.Object ref = producer_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        producer_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string producer = 3;</code>
     */
    public Builder setProducer(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      producer_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required string producer = 3;</code>
     */
    public Builder clearProducer() {
      bitField0_ = (bitField0_ & ~0x00000004);
      producer_ = getDefaultInstance().getProducer();
      onChanged();
      return this;
    }
    /**
     * <code>required string producer = 3;</code>
     */
    public Builder setProducerBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      producer_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object releaseDate_ = "";
    /**
     * <code>optional string release_date = 4;</code>
     */
    public boolean hasReleaseDate() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string release_date = 4;</code>
     */
    public java.lang.String getReleaseDate() {
      java.lang.Object ref = releaseDate_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          releaseDate_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string release_date = 4;</code>
     */
    public com.google.protobuf.ByteString
        getReleaseDateBytes() {
      java.lang.Object ref = releaseDate_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        releaseDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string release_date = 4;</code>
     */
    public Builder setReleaseDate(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
      releaseDate_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string release_date = 4;</code>
     */
    public Builder clearReleaseDate() {
      bitField0_ = (bitField0_ & ~0x00000008);
      releaseDate_ = getDefaultInstance().getReleaseDate();
      onChanged();
      return this;
    }
    /**
     * <code>optional string release_date = 4;</code>
     */
    public Builder setReleaseDateBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
      releaseDate_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList character_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureCharacterIsMutable() {
      if (!((bitField0_ & 0x00000010) == 0x00000010)) {
        character_ = new com.google.protobuf.LazyStringArrayList(character_);
        bitField0_ |= 0x00000010;
       }
    }
    /**
     * <code>repeated string character = 5;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getCharacterList() {
      return character_.getUnmodifiableView();
    }
    /**
     * <code>repeated string character = 5;</code>
     */
    public int getCharacterCount() {
      return character_.size();
    }
    /**
     * <code>repeated string character = 5;</code>
     */
    public java.lang.String getCharacter(int index) {
      return character_.get(index);
    }
    /**
     * <code>repeated string character = 5;</code>
     */
    public com.google.protobuf.ByteString
        getCharacterBytes(int index) {
      return character_.getByteString(index);
    }
    /**
     * <code>repeated string character = 5;</code>
     */
    public Builder setCharacter(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureCharacterIsMutable();
      character_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string character = 5;</code>
     */
    public Builder addCharacter(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureCharacterIsMutable();
      character_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string character = 5;</code>
     */
    public Builder addAllCharacter(
        java.lang.Iterable<java.lang.String> values) {
      ensureCharacterIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, character_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string character = 5;</code>
     */
    public Builder clearCharacter() {
      character_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string character = 5;</code>
     */
    public Builder addCharacterBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureCharacterIsMutable();
      character_.add(value);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ch3.ex1.Film)
  }

  // @@protoc_insertion_point(class_scope:ch3.ex1.Film)
  private static final uk.me.uohiro.protobuf.model.ch3.ex1.Film DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new uk.me.uohiro.protobuf.model.ch3.ex1.Film();
  }

  public static uk.me.uohiro.protobuf.model.ch3.ex1.Film getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<Film>
      PARSER = new com.google.protobuf.AbstractParser<Film>() {
    @java.lang.Override
    public Film parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Film(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Film> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Film> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public uk.me.uohiro.protobuf.model.ch3.ex1.Film getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

