// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ch3/ex2.proto

package uk.me.uohiro.protobuf.model.ch3.ex2;

public interface OtherFilmOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ch3.ex2.OtherFilm)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .ch3.ex2.Film.Character characters = 1;</code>
   */
  java.util.List<uk.me.uohiro.protobuf.model.ch3.ex2.Film.Character> 
      getCharactersList();
  /**
   * <code>repeated .ch3.ex2.Film.Character characters = 1;</code>
   */
  uk.me.uohiro.protobuf.model.ch3.ex2.Film.Character getCharacters(int index);
  /**
   * <code>repeated .ch3.ex2.Film.Character characters = 1;</code>
   */
  int getCharactersCount();
  /**
   * <code>repeated .ch3.ex2.Film.Character characters = 1;</code>
   */
  java.util.List<? extends uk.me.uohiro.protobuf.model.ch3.ex2.Film.CharacterOrBuilder> 
      getCharactersOrBuilderList();
  /**
   * <code>repeated .ch3.ex2.Film.Character characters = 1;</code>
   */
  uk.me.uohiro.protobuf.model.ch3.ex2.Film.CharacterOrBuilder getCharactersOrBuilder(
      int index);
}
