// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: extras/ex3/flow_control.proto

package uk.me.uohiro.protobuf.model.extras.ex3;

public final class SayHelloAPIProto {
  private SayHelloAPIProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_extras_ex3_HelloRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_extras_ex3_HelloRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_extras_ex3_HelloResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_extras_ex3_HelloResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035extras/ex3/flow_control.proto\022\nextras." +
      "ex3\"\034\n\014HelloRequest\022\014\n\004name\030\001 \001(\t\" \n\rHel" +
      "loResponse\022\017\n\007message\030\001 \001(\t2`\n\020Streaming" +
      "Greeter\022L\n\021SayHelloStreaming\022\030.extras.ex" +
      "3.HelloRequest\032\031.extras.ex3.HelloRespons" +
      "e(\0010\001B>\n&uk.me.uohiro.protobuf.model.ext" +
      "ras.ex3B\020SayHelloAPIProtoH\001P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_extras_ex3_HelloRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_extras_ex3_HelloRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_extras_ex3_HelloRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_extras_ex3_HelloResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_extras_ex3_HelloResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_extras_ex3_HelloResponse_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
