// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ch10/ex2/boxing.proto

package uk.me.uohiro.protobuf.model.ch10.ex2;

/**
 * Protobuf type {@code ch10.ex2.BoxingRequest}
 */
public  final class BoxingRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ch10.ex2.BoxingRequest)
    BoxingRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use BoxingRequest.newBuilder() to construct.
  private BoxingRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BoxingRequest() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private BoxingRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.google.protobuf.StringValue.Builder subBuilder = null;
            if (stringValue1_ != null) {
              subBuilder = stringValue1_.toBuilder();
            }
            stringValue1_ = input.readMessage(com.google.protobuf.StringValue.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(stringValue1_);
              stringValue1_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            com.google.protobuf.StringValue.Builder subBuilder = null;
            if (stringValue2_ != null) {
              subBuilder = stringValue2_.toBuilder();
            }
            stringValue2_ = input.readMessage(com.google.protobuf.StringValue.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(stringValue2_);
              stringValue2_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            com.google.protobuf.Int32Value.Builder subBuilder = null;
            if (int32Value1_ != null) {
              subBuilder = int32Value1_.toBuilder();
            }
            int32Value1_ = input.readMessage(com.google.protobuf.Int32Value.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(int32Value1_);
              int32Value1_ = subBuilder.buildPartial();
            }

            break;
          }
          case 34: {
            com.google.protobuf.Int32Value.Builder subBuilder = null;
            if (int32Value2_ != null) {
              subBuilder = int32Value2_.toBuilder();
            }
            int32Value2_ = input.readMessage(com.google.protobuf.Int32Value.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(int32Value2_);
              int32Value2_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return uk.me.uohiro.protobuf.model.ch10.ex2.BoxingAPIProto.internal_static_ch10_ex2_BoxingRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return uk.me.uohiro.protobuf.model.ch10.ex2.BoxingAPIProto.internal_static_ch10_ex2_BoxingRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            uk.me.uohiro.protobuf.model.ch10.ex2.BoxingRequest.class, uk.me.uohiro.protobuf.model.ch10.ex2.BoxingRequest.Builder.class);
  }

  public static final int STRING_VALUE1_FIELD_NUMBER = 1;
  private com.google.protobuf.StringValue stringValue1_;
  /**
   * <code>.google.protobuf.StringValue string_value1 = 1;</code>
   */
  public boolean hasStringValue1() {
    return stringValue1_ != null;
  }
  /**
   * <code>.google.protobuf.StringValue string_value1 = 1;</code>
   */
  public com.google.protobuf.StringValue getStringValue1() {
    return stringValue1_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : stringValue1_;
  }
  /**
   * <code>.google.protobuf.StringValue string_value1 = 1;</code>
   */
  public com.google.protobuf.StringValueOrBuilder getStringValue1OrBuilder() {
    return getStringValue1();
  }

  public static final int STRING_VALUE2_FIELD_NUMBER = 2;
  private com.google.protobuf.StringValue stringValue2_;
  /**
   * <code>.google.protobuf.StringValue string_value2 = 2;</code>
   */
  public boolean hasStringValue2() {
    return stringValue2_ != null;
  }
  /**
   * <code>.google.protobuf.StringValue string_value2 = 2;</code>
   */
  public com.google.protobuf.StringValue getStringValue2() {
    return stringValue2_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : stringValue2_;
  }
  /**
   * <code>.google.protobuf.StringValue string_value2 = 2;</code>
   */
  public com.google.protobuf.StringValueOrBuilder getStringValue2OrBuilder() {
    return getStringValue2();
  }

  public static final int INT32_VALUE1_FIELD_NUMBER = 3;
  private com.google.protobuf.Int32Value int32Value1_;
  /**
   * <code>.google.protobuf.Int32Value int32_value1 = 3;</code>
   */
  public boolean hasInt32Value1() {
    return int32Value1_ != null;
  }
  /**
   * <code>.google.protobuf.Int32Value int32_value1 = 3;</code>
   */
  public com.google.protobuf.Int32Value getInt32Value1() {
    return int32Value1_ == null ? com.google.protobuf.Int32Value.getDefaultInstance() : int32Value1_;
  }
  /**
   * <code>.google.protobuf.Int32Value int32_value1 = 3;</code>
   */
  public com.google.protobuf.Int32ValueOrBuilder getInt32Value1OrBuilder() {
    return getInt32Value1();
  }

  public static final int INT32_VALUE2_FIELD_NUMBER = 4;
  private com.google.protobuf.Int32Value int32Value2_;
  /**
   * <code>.google.protobuf.Int32Value int32_value2 = 4;</code>
   */
  public boolean hasInt32Value2() {
    return int32Value2_ != null;
  }
  /**
   * <code>.google.protobuf.Int32Value int32_value2 = 4;</code>
   */
  public com.google.protobuf.Int32Value getInt32Value2() {
    return int32Value2_ == null ? com.google.protobuf.Int32Value.getDefaultInstance() : int32Value2_;
  }
  /**
   * <code>.google.protobuf.Int32Value int32_value2 = 4;</code>
   */
  public com.google.protobuf.Int32ValueOrBuilder getInt32Value2OrBuilder() {
    return getInt32Value2();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (stringValue1_ != null) {
      output.writeMessage(1, getStringValue1());
    }
    if (stringValue2_ != null) {
      output.writeMessage(2, getStringValue2());
    }
    if (int32Value1_ != null) {
      output.writeMessage(3, getInt32Value1());
    }
    if (int32Value2_ != null) {
      output.writeMessage(4, getInt32Value2());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (stringValue1_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getStringValue1());
    }
    if (stringValue2_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getStringValue2());
    }
    if (int32Value1_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getInt32Value1());
    }
    if (int32Value2_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getInt32Value2());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof uk.me.uohiro.protobuf.model.ch10.ex2.BoxingRequest)) {
      return super.equals(obj);
    }
    uk.me.uohiro.protobuf.model.ch10.ex2.BoxingRequest other = (uk.me.uohiro.protobuf.model.ch10.ex2.BoxingRequest) obj;

    boolean result = true;
    result = result && (hasStringValue1() == other.hasStringValue1());
    if (hasStringValue1()) {
      result = result && getStringValue1()
          .equals(other.getStringValue1());
    }
    result = result && (hasStringValue2() == other.hasStringValue2());
    if (hasStringValue2()) {
      result = result && getStringValue2()
          .equals(other.getStringValue2());
    }
    result = result && (hasInt32Value1() == other.hasInt32Value1());
    if (hasInt32Value1()) {
      result = result && getInt32Value1()
          .equals(other.getInt32Value1());
    }
    result = result && (hasInt32Value2() == other.hasInt32Value2());
    if (hasInt32Value2()) {
      result = result && getInt32Value2()
          .equals(other.getInt32Value2());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasStringValue1()) {
      hash = (37 * hash) + STRING_VALUE1_FIELD_NUMBER;
      hash = (53 * hash) + getStringValue1().hashCode();
    }
    if (hasStringValue2()) {
      hash = (37 * hash) + STRING_VALUE2_FIELD_NUMBER;
      hash = (53 * hash) + getStringValue2().hashCode();
    }
    if (hasInt32Value1()) {
      hash = (37 * hash) + INT32_VALUE1_FIELD_NUMBER;
      hash = (53 * hash) + getInt32Value1().hashCode();
    }
    if (hasInt32Value2()) {
      hash = (37 * hash) + INT32_VALUE2_FIELD_NUMBER;
      hash = (53 * hash) + getInt32Value2().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static uk.me.uohiro.protobuf.model.ch10.ex2.BoxingRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static uk.me.uohiro.protobuf.model.ch10.ex2.BoxingRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static uk.me.uohiro.protobuf.model.ch10.ex2.BoxingRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static uk.me.uohiro.protobuf.model.ch10.ex2.BoxingRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static uk.me.uohiro.protobuf.model.ch10.ex2.BoxingRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static uk.me.uohiro.protobuf.model.ch10.ex2.BoxingRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static uk.me.uohiro.protobuf.model.ch10.ex2.BoxingRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static uk.me.uohiro.protobuf.model.ch10.ex2.BoxingRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static uk.me.uohiro.protobuf.model.ch10.ex2.BoxingRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static uk.me.uohiro.protobuf.model.ch10.ex2.BoxingRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static uk.me.uohiro.protobuf.model.ch10.ex2.BoxingRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static uk.me.uohiro.protobuf.model.ch10.ex2.BoxingRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(uk.me.uohiro.protobuf.model.ch10.ex2.BoxingRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ch10.ex2.BoxingRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ch10.ex2.BoxingRequest)
      uk.me.uohiro.protobuf.model.ch10.ex2.BoxingRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return uk.me.uohiro.protobuf.model.ch10.ex2.BoxingAPIProto.internal_static_ch10_ex2_BoxingRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return uk.me.uohiro.protobuf.model.ch10.ex2.BoxingAPIProto.internal_static_ch10_ex2_BoxingRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              uk.me.uohiro.protobuf.model.ch10.ex2.BoxingRequest.class, uk.me.uohiro.protobuf.model.ch10.ex2.BoxingRequest.Builder.class);
    }

    // Construct using uk.me.uohiro.protobuf.model.ch10.ex2.BoxingRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (stringValue1Builder_ == null) {
        stringValue1_ = null;
      } else {
        stringValue1_ = null;
        stringValue1Builder_ = null;
      }
      if (stringValue2Builder_ == null) {
        stringValue2_ = null;
      } else {
        stringValue2_ = null;
        stringValue2Builder_ = null;
      }
      if (int32Value1Builder_ == null) {
        int32Value1_ = null;
      } else {
        int32Value1_ = null;
        int32Value1Builder_ = null;
      }
      if (int32Value2Builder_ == null) {
        int32Value2_ = null;
      } else {
        int32Value2_ = null;
        int32Value2Builder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return uk.me.uohiro.protobuf.model.ch10.ex2.BoxingAPIProto.internal_static_ch10_ex2_BoxingRequest_descriptor;
    }

    @java.lang.Override
    public uk.me.uohiro.protobuf.model.ch10.ex2.BoxingRequest getDefaultInstanceForType() {
      return uk.me.uohiro.protobuf.model.ch10.ex2.BoxingRequest.getDefaultInstance();
    }

    @java.lang.Override
    public uk.me.uohiro.protobuf.model.ch10.ex2.BoxingRequest build() {
      uk.me.uohiro.protobuf.model.ch10.ex2.BoxingRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public uk.me.uohiro.protobuf.model.ch10.ex2.BoxingRequest buildPartial() {
      uk.me.uohiro.protobuf.model.ch10.ex2.BoxingRequest result = new uk.me.uohiro.protobuf.model.ch10.ex2.BoxingRequest(this);
      if (stringValue1Builder_ == null) {
        result.stringValue1_ = stringValue1_;
      } else {
        result.stringValue1_ = stringValue1Builder_.build();
      }
      if (stringValue2Builder_ == null) {
        result.stringValue2_ = stringValue2_;
      } else {
        result.stringValue2_ = stringValue2Builder_.build();
      }
      if (int32Value1Builder_ == null) {
        result.int32Value1_ = int32Value1_;
      } else {
        result.int32Value1_ = int32Value1Builder_.build();
      }
      if (int32Value2Builder_ == null) {
        result.int32Value2_ = int32Value2_;
      } else {
        result.int32Value2_ = int32Value2Builder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof uk.me.uohiro.protobuf.model.ch10.ex2.BoxingRequest) {
        return mergeFrom((uk.me.uohiro.protobuf.model.ch10.ex2.BoxingRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(uk.me.uohiro.protobuf.model.ch10.ex2.BoxingRequest other) {
      if (other == uk.me.uohiro.protobuf.model.ch10.ex2.BoxingRequest.getDefaultInstance()) return this;
      if (other.hasStringValue1()) {
        mergeStringValue1(other.getStringValue1());
      }
      if (other.hasStringValue2()) {
        mergeStringValue2(other.getStringValue2());
      }
      if (other.hasInt32Value1()) {
        mergeInt32Value1(other.getInt32Value1());
      }
      if (other.hasInt32Value2()) {
        mergeInt32Value2(other.getInt32Value2());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      uk.me.uohiro.protobuf.model.ch10.ex2.BoxingRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (uk.me.uohiro.protobuf.model.ch10.ex2.BoxingRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.google.protobuf.StringValue stringValue1_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> stringValue1Builder_;
    /**
     * <code>.google.protobuf.StringValue string_value1 = 1;</code>
     */
    public boolean hasStringValue1() {
      return stringValue1Builder_ != null || stringValue1_ != null;
    }
    /**
     * <code>.google.protobuf.StringValue string_value1 = 1;</code>
     */
    public com.google.protobuf.StringValue getStringValue1() {
      if (stringValue1Builder_ == null) {
        return stringValue1_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : stringValue1_;
      } else {
        return stringValue1Builder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.StringValue string_value1 = 1;</code>
     */
    public Builder setStringValue1(com.google.protobuf.StringValue value) {
      if (stringValue1Builder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        stringValue1_ = value;
        onChanged();
      } else {
        stringValue1Builder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue string_value1 = 1;</code>
     */
    public Builder setStringValue1(
        com.google.protobuf.StringValue.Builder builderForValue) {
      if (stringValue1Builder_ == null) {
        stringValue1_ = builderForValue.build();
        onChanged();
      } else {
        stringValue1Builder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue string_value1 = 1;</code>
     */
    public Builder mergeStringValue1(com.google.protobuf.StringValue value) {
      if (stringValue1Builder_ == null) {
        if (stringValue1_ != null) {
          stringValue1_ =
            com.google.protobuf.StringValue.newBuilder(stringValue1_).mergeFrom(value).buildPartial();
        } else {
          stringValue1_ = value;
        }
        onChanged();
      } else {
        stringValue1Builder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue string_value1 = 1;</code>
     */
    public Builder clearStringValue1() {
      if (stringValue1Builder_ == null) {
        stringValue1_ = null;
        onChanged();
      } else {
        stringValue1_ = null;
        stringValue1Builder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue string_value1 = 1;</code>
     */
    public com.google.protobuf.StringValue.Builder getStringValue1Builder() {
      
      onChanged();
      return getStringValue1FieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.StringValue string_value1 = 1;</code>
     */
    public com.google.protobuf.StringValueOrBuilder getStringValue1OrBuilder() {
      if (stringValue1Builder_ != null) {
        return stringValue1Builder_.getMessageOrBuilder();
      } else {
        return stringValue1_ == null ?
            com.google.protobuf.StringValue.getDefaultInstance() : stringValue1_;
      }
    }
    /**
     * <code>.google.protobuf.StringValue string_value1 = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> 
        getStringValue1FieldBuilder() {
      if (stringValue1Builder_ == null) {
        stringValue1Builder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder>(
                getStringValue1(),
                getParentForChildren(),
                isClean());
        stringValue1_ = null;
      }
      return stringValue1Builder_;
    }

    private com.google.protobuf.StringValue stringValue2_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> stringValue2Builder_;
    /**
     * <code>.google.protobuf.StringValue string_value2 = 2;</code>
     */
    public boolean hasStringValue2() {
      return stringValue2Builder_ != null || stringValue2_ != null;
    }
    /**
     * <code>.google.protobuf.StringValue string_value2 = 2;</code>
     */
    public com.google.protobuf.StringValue getStringValue2() {
      if (stringValue2Builder_ == null) {
        return stringValue2_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : stringValue2_;
      } else {
        return stringValue2Builder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.StringValue string_value2 = 2;</code>
     */
    public Builder setStringValue2(com.google.protobuf.StringValue value) {
      if (stringValue2Builder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        stringValue2_ = value;
        onChanged();
      } else {
        stringValue2Builder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue string_value2 = 2;</code>
     */
    public Builder setStringValue2(
        com.google.protobuf.StringValue.Builder builderForValue) {
      if (stringValue2Builder_ == null) {
        stringValue2_ = builderForValue.build();
        onChanged();
      } else {
        stringValue2Builder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue string_value2 = 2;</code>
     */
    public Builder mergeStringValue2(com.google.protobuf.StringValue value) {
      if (stringValue2Builder_ == null) {
        if (stringValue2_ != null) {
          stringValue2_ =
            com.google.protobuf.StringValue.newBuilder(stringValue2_).mergeFrom(value).buildPartial();
        } else {
          stringValue2_ = value;
        }
        onChanged();
      } else {
        stringValue2Builder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue string_value2 = 2;</code>
     */
    public Builder clearStringValue2() {
      if (stringValue2Builder_ == null) {
        stringValue2_ = null;
        onChanged();
      } else {
        stringValue2_ = null;
        stringValue2Builder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue string_value2 = 2;</code>
     */
    public com.google.protobuf.StringValue.Builder getStringValue2Builder() {
      
      onChanged();
      return getStringValue2FieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.StringValue string_value2 = 2;</code>
     */
    public com.google.protobuf.StringValueOrBuilder getStringValue2OrBuilder() {
      if (stringValue2Builder_ != null) {
        return stringValue2Builder_.getMessageOrBuilder();
      } else {
        return stringValue2_ == null ?
            com.google.protobuf.StringValue.getDefaultInstance() : stringValue2_;
      }
    }
    /**
     * <code>.google.protobuf.StringValue string_value2 = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> 
        getStringValue2FieldBuilder() {
      if (stringValue2Builder_ == null) {
        stringValue2Builder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder>(
                getStringValue2(),
                getParentForChildren(),
                isClean());
        stringValue2_ = null;
      }
      return stringValue2Builder_;
    }

    private com.google.protobuf.Int32Value int32Value1_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder> int32Value1Builder_;
    /**
     * <code>.google.protobuf.Int32Value int32_value1 = 3;</code>
     */
    public boolean hasInt32Value1() {
      return int32Value1Builder_ != null || int32Value1_ != null;
    }
    /**
     * <code>.google.protobuf.Int32Value int32_value1 = 3;</code>
     */
    public com.google.protobuf.Int32Value getInt32Value1() {
      if (int32Value1Builder_ == null) {
        return int32Value1_ == null ? com.google.protobuf.Int32Value.getDefaultInstance() : int32Value1_;
      } else {
        return int32Value1Builder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Int32Value int32_value1 = 3;</code>
     */
    public Builder setInt32Value1(com.google.protobuf.Int32Value value) {
      if (int32Value1Builder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        int32Value1_ = value;
        onChanged();
      } else {
        int32Value1Builder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int32Value int32_value1 = 3;</code>
     */
    public Builder setInt32Value1(
        com.google.protobuf.Int32Value.Builder builderForValue) {
      if (int32Value1Builder_ == null) {
        int32Value1_ = builderForValue.build();
        onChanged();
      } else {
        int32Value1Builder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int32Value int32_value1 = 3;</code>
     */
    public Builder mergeInt32Value1(com.google.protobuf.Int32Value value) {
      if (int32Value1Builder_ == null) {
        if (int32Value1_ != null) {
          int32Value1_ =
            com.google.protobuf.Int32Value.newBuilder(int32Value1_).mergeFrom(value).buildPartial();
        } else {
          int32Value1_ = value;
        }
        onChanged();
      } else {
        int32Value1Builder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int32Value int32_value1 = 3;</code>
     */
    public Builder clearInt32Value1() {
      if (int32Value1Builder_ == null) {
        int32Value1_ = null;
        onChanged();
      } else {
        int32Value1_ = null;
        int32Value1Builder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int32Value int32_value1 = 3;</code>
     */
    public com.google.protobuf.Int32Value.Builder getInt32Value1Builder() {
      
      onChanged();
      return getInt32Value1FieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Int32Value int32_value1 = 3;</code>
     */
    public com.google.protobuf.Int32ValueOrBuilder getInt32Value1OrBuilder() {
      if (int32Value1Builder_ != null) {
        return int32Value1Builder_.getMessageOrBuilder();
      } else {
        return int32Value1_ == null ?
            com.google.protobuf.Int32Value.getDefaultInstance() : int32Value1_;
      }
    }
    /**
     * <code>.google.protobuf.Int32Value int32_value1 = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder> 
        getInt32Value1FieldBuilder() {
      if (int32Value1Builder_ == null) {
        int32Value1Builder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder>(
                getInt32Value1(),
                getParentForChildren(),
                isClean());
        int32Value1_ = null;
      }
      return int32Value1Builder_;
    }

    private com.google.protobuf.Int32Value int32Value2_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder> int32Value2Builder_;
    /**
     * <code>.google.protobuf.Int32Value int32_value2 = 4;</code>
     */
    public boolean hasInt32Value2() {
      return int32Value2Builder_ != null || int32Value2_ != null;
    }
    /**
     * <code>.google.protobuf.Int32Value int32_value2 = 4;</code>
     */
    public com.google.protobuf.Int32Value getInt32Value2() {
      if (int32Value2Builder_ == null) {
        return int32Value2_ == null ? com.google.protobuf.Int32Value.getDefaultInstance() : int32Value2_;
      } else {
        return int32Value2Builder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Int32Value int32_value2 = 4;</code>
     */
    public Builder setInt32Value2(com.google.protobuf.Int32Value value) {
      if (int32Value2Builder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        int32Value2_ = value;
        onChanged();
      } else {
        int32Value2Builder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int32Value int32_value2 = 4;</code>
     */
    public Builder setInt32Value2(
        com.google.protobuf.Int32Value.Builder builderForValue) {
      if (int32Value2Builder_ == null) {
        int32Value2_ = builderForValue.build();
        onChanged();
      } else {
        int32Value2Builder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int32Value int32_value2 = 4;</code>
     */
    public Builder mergeInt32Value2(com.google.protobuf.Int32Value value) {
      if (int32Value2Builder_ == null) {
        if (int32Value2_ != null) {
          int32Value2_ =
            com.google.protobuf.Int32Value.newBuilder(int32Value2_).mergeFrom(value).buildPartial();
        } else {
          int32Value2_ = value;
        }
        onChanged();
      } else {
        int32Value2Builder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int32Value int32_value2 = 4;</code>
     */
    public Builder clearInt32Value2() {
      if (int32Value2Builder_ == null) {
        int32Value2_ = null;
        onChanged();
      } else {
        int32Value2_ = null;
        int32Value2Builder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int32Value int32_value2 = 4;</code>
     */
    public com.google.protobuf.Int32Value.Builder getInt32Value2Builder() {
      
      onChanged();
      return getInt32Value2FieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Int32Value int32_value2 = 4;</code>
     */
    public com.google.protobuf.Int32ValueOrBuilder getInt32Value2OrBuilder() {
      if (int32Value2Builder_ != null) {
        return int32Value2Builder_.getMessageOrBuilder();
      } else {
        return int32Value2_ == null ?
            com.google.protobuf.Int32Value.getDefaultInstance() : int32Value2_;
      }
    }
    /**
     * <code>.google.protobuf.Int32Value int32_value2 = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder> 
        getInt32Value2FieldBuilder() {
      if (int32Value2Builder_ == null) {
        int32Value2Builder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder>(
                getInt32Value2(),
                getParentForChildren(),
                isClean());
        int32Value2_ = null;
      }
      return int32Value2Builder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ch10.ex2.BoxingRequest)
  }

  // @@protoc_insertion_point(class_scope:ch10.ex2.BoxingRequest)
  private static final uk.me.uohiro.protobuf.model.ch10.ex2.BoxingRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new uk.me.uohiro.protobuf.model.ch10.ex2.BoxingRequest();
  }

  public static uk.me.uohiro.protobuf.model.ch10.ex2.BoxingRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BoxingRequest>
      PARSER = new com.google.protobuf.AbstractParser<BoxingRequest>() {
    @java.lang.Override
    public BoxingRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new BoxingRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<BoxingRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BoxingRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public uk.me.uohiro.protobuf.model.ch10.ex2.BoxingRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

