// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ch10/ex2/boxing.proto

package uk.me.uohiro.protobuf.model.ch10.ex2;

public final class VersioningAPIProto {
  private VersioningAPIProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ch10_ex2_BoxingRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ch10_ex2_BoxingRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ch10_ex2_BoxingResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ch10_ex2_BoxingResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025ch10/ex2/boxing.proto\022\010ch10.ex2\032\036googl" +
      "e/protobuf/wrappers.proto\"\337\001\n\rBoxingRequ" +
      "est\0223\n\rstring_value1\030\001 \001(\0132\034.google.prot" +
      "obuf.StringValue\0223\n\rstring_value2\030\002 \001(\0132" +
      "\034.google.protobuf.StringValue\0221\n\014int32_v" +
      "alue1\030\003 \001(\0132\033.google.protobuf.Int32Value" +
      "\0221\n\014int32_value2\030\004 \001(\0132\033.google.protobuf" +
      ".Int32Value\"\340\001\n\016BoxingResponse\0223\n\rstring" +
      "_value1\030\001 \001(\0132\034.google.protobuf.StringVa" +
      "lue\0223\n\rstring_value2\030\002 \001(\0132\034.google.prot" +
      "obuf.StringValue\0221\n\014int32_value1\030\003 \001(\0132\033" +
      ".google.protobuf.Int32Value\0221\n\014int32_val" +
      "ue2\030\004 \001(\0132\033.google.protobuf.Int32Value2T" +
      "\n\rBoxingService\022C\n\016ProcessRequest\022\027.ch10" +
      ".ex2.BoxingRequest\032\030.ch10.ex2.BoxingResp" +
      "onseB>\n$uk.me.uohiro.protobuf.model.ch10" +
      ".ex2B\022VersioningAPIProtoH\001P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.WrappersProto.getDescriptor(),
        }, assigner);
    internal_static_ch10_ex2_BoxingRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ch10_ex2_BoxingRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ch10_ex2_BoxingRequest_descriptor,
        new java.lang.String[] { "StringValue1", "StringValue2", "Int32Value1", "Int32Value2", });
    internal_static_ch10_ex2_BoxingResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ch10_ex2_BoxingResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ch10_ex2_BoxingResponse_descriptor,
        new java.lang.String[] { "StringValue1", "StringValue2", "Int32Value1", "Int32Value2", });
    com.google.protobuf.WrappersProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
