// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ch6/database.proto

package uk.me.uohiro.protobuf.model.ch6;

public final class DatabaseServiceProto {
  private DatabaseServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ch6_SearchRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ch6_SearchRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ch6_SearchResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ch6_SearchResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022ch6/database.proto\022\003ch6\"2\n\rSearchReque" +
      "st\022\014\n\004term\030\001 \001(\t\022\023\n\013max_results\030\002 \001(\003\"E\n" +
      "\016SearchResponse\022\024\n\014matched_term\030\001 \001(\t\022\017\n" +
      "\007content\030\002 \001(\t\022\014\n\004rank\030\003 \001(\0052?\n\010Database" +
      "\0223\n\006Search\022\022.ch6.SearchRequest\032\023.ch6.Sea" +
      "rchResponse0\001B;\n\037uk.me.uohiro.protobuf.m" +
      "odel.ch6B\024DatabaseServiceProtoH\001P\001b\006prot" +
      "o3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ch6_SearchRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ch6_SearchRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ch6_SearchRequest_descriptor,
        new java.lang.String[] { "Term", "MaxResults", });
    internal_static_ch6_SearchResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ch6_SearchResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ch6_SearchResponse_descriptor,
        new java.lang.String[] { "MatchedTerm", "Content", "Rank", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
