// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: extras/ex2/weather.proto

package uk.me.uohiro.protobuf.model.extras.ex2;

public interface CoordinatesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:extras.ex2.Coordinates)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>fixed64 latitude = 1;</code>
   */
  long getLatitude();

  /**
   * <code>fixed64 longitude = 2;</code>
   */
  long getLongitude();
}
