// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: extras/ex2/weather.proto

package uk.me.uohiro.protobuf.model.extras.ex2;

public interface WeatherRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:extras.ex2.WeatherRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.extras.ex2.Coordinates coordinates = 1;</code>
   */
  boolean hasCoordinates();
  /**
   * <code>.extras.ex2.Coordinates coordinates = 1;</code>
   */
  uk.me.uohiro.protobuf.model.extras.ex2.Coordinates getCoordinates();
  /**
   * <code>.extras.ex2.Coordinates coordinates = 1;</code>
   */
  uk.me.uohiro.protobuf.model.extras.ex2.CoordinatesOrBuilder getCoordinatesOrBuilder();
}
