// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: extras/ex2/weather.proto

package uk.me.uohiro.protobuf.model.extras.ex2;

public final class WeatherAPIProto {
  private WeatherAPIProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_extras_ex2_WeatherRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_extras_ex2_WeatherRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_extras_ex2_Coordinates_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_extras_ex2_Coordinates_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_extras_ex2_WeatherResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_extras_ex2_WeatherResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_extras_ex2_Temperature_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_extras_ex2_Temperature_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_extras_ex2_HumidityResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_extras_ex2_HumidityResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_extras_ex2_Wind_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_extras_ex2_Wind_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_extras_ex2_Speed_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_extras_ex2_Speed_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030extras/ex2/weather.proto\022\nextras.ex2\">" +
      "\n\016WeatherRequest\022,\n\013coordinates\030\001 \001(\0132\027." +
      "extras.ex2.Coordinates\"2\n\013Coordinates\022\020\n" +
      "\010latitude\030\001 \001(\006\022\021\n\tlongitude\030\002 \001(\006\"q\n\017We" +
      "atherResponse\022,\n\013temperature\030\001 \001(\0132\027.ext" +
      "ras.ex2.Temperature\022\020\n\010humidity\030\002 \001(\002\022\036\n" +
      "\004wind\030\003 \001(\0132\020.extras.ex2.Wind\"~\n\013Tempera" +
      "ture\022\017\n\007degrees\030\001 \001(\002\022,\n\005units\030\002 \001(\0162\035.e" +
      "xtras.ex2.Temperature.Units\"0\n\005Units\022\016\n\n" +
      "FAHRENHEIT\020\000\022\013\n\007CELCIUS\020\001\022\n\n\006KELVIN\020\002\"$\n" +
      "\020HumidityResponse\022\020\n\010humidity\030\001 \001(\002\";\n\004W" +
      "ind\022 \n\005speed\030\001 \001(\0132\021.extras.ex2.Speed\022\021\n" +
      "\tdirection\030\002 \001(\002\"m\n\005Speed\022\r\n\005value\030\001 \001(\002" +
      "\022&\n\005units\030\002 \001(\0162\027.extras.ex2.Speed.Units" +
      "\"-\n\005Units\022\007\n\003MPH\020\000\022\007\n\003MPS\020\001\022\t\n\005KNOTS\020\002\022\007" +
      "\n\003KMH\020\0032P\n\007Weather\022E\n\nGetCurrent\022\032.extra" +
      "s.ex2.WeatherRequest\032\033.extras.ex2.Weathe" +
      "rResponse2T\n\022TemperatureService\022>\n\nGetCu" +
      "rrent\022\027.extras.ex2.Coordinates\032\027.extras." +
      "ex2.Temperature2V\n\017HumidityService\022C\n\nGe" +
      "tCurrent\022\027.extras.ex2.Coordinates\032\034.extr" +
      "as.ex2.HumidityResponse2F\n\013WindService\0227" +
      "\n\nGetCurrent\022\027.extras.ex2.Coordinates\032\020." +
      "extras.ex2.WindB=\n&uk.me.uohiro.protobuf" +
      ".model.extras.ex2B\017WeatherAPIProtoH\001P\001b\006" +
      "proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_extras_ex2_WeatherRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_extras_ex2_WeatherRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_extras_ex2_WeatherRequest_descriptor,
        new java.lang.String[] { "Coordinates", });
    internal_static_extras_ex2_Coordinates_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_extras_ex2_Coordinates_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_extras_ex2_Coordinates_descriptor,
        new java.lang.String[] { "Latitude", "Longitude", });
    internal_static_extras_ex2_WeatherResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_extras_ex2_WeatherResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_extras_ex2_WeatherResponse_descriptor,
        new java.lang.String[] { "Temperature", "Humidity", "Wind", });
    internal_static_extras_ex2_Temperature_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_extras_ex2_Temperature_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_extras_ex2_Temperature_descriptor,
        new java.lang.String[] { "Degrees", "Units", });
    internal_static_extras_ex2_HumidityResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_extras_ex2_HumidityResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_extras_ex2_HumidityResponse_descriptor,
        new java.lang.String[] { "Humidity", });
    internal_static_extras_ex2_Wind_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_extras_ex2_Wind_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_extras_ex2_Wind_descriptor,
        new java.lang.String[] { "Speed", "Direction", });
    internal_static_extras_ex2_Speed_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_extras_ex2_Speed_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_extras_ex2_Speed_descriptor,
        new java.lang.String[] { "Value", "Units", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
