// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ch7/deadline.proto

package uk.me.uohiro.protobuf.model.ch7.ex4;

public interface DeadlineResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ch7.ex4.DeadlineResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
