// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ch7/oauth_authentication.proto

package uk.me.uohiro.protobuf.model.ch7.ex3;

public interface GetDataRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ch7.ex3.GetDataRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();
}
