// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ch7/oauth_authentication.proto

package uk.me.uohiro.protobuf.model.ch7.ex3;

public final class ProtectedResourceAPIProto {
  private ProtectedResourceAPIProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ch7_ex3_GetDataRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ch7_ex3_GetDataRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ch7_ex3_GetDataResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ch7_ex3_GetDataResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036ch7/oauth_authentication.proto\022\007ch7.ex" +
      "3\"\034\n\016GetDataRequest\022\n\n\002id\030\001 \001(\t\"\037\n\017GetDa" +
      "taResponse\022\014\n\004data\030\002 \001(\t2Q\n\021ProtectedRes" +
      "ource\022<\n\007GetData\022\027.ch7.ex3.GetDataReques" +
      "t\032\030.ch7.ex3.GetDataResponseBD\n#uk.me.uoh" +
      "iro.protobuf.model.ch7.ex3B\031ProtectedRes" +
      "ourceAPIProtoH\001P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ch7_ex3_GetDataRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ch7_ex3_GetDataRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ch7_ex3_GetDataRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_ch7_ex3_GetDataResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ch7_ex3_GetDataResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ch7_ex3_GetDataResponse_descriptor,
        new java.lang.String[] { "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
