// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: extras/ex1/weather.proto

package uk.me.uohiro.protobuf.model.extras.ex1;

/**
 * Protobuf type {@code extras.ex1.Temperature}
 */
public  final class Temperature extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:extras.ex1.Temperature)
    TemperatureOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Temperature.newBuilder() to construct.
  private Temperature(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Temperature() {
    degrees_ = 0F;
    units_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Temperature(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 13: {

            degrees_ = input.readFloat();
            break;
          }
          case 16: {
            int rawValue = input.readEnum();

            units_ = rawValue;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return uk.me.uohiro.protobuf.model.extras.ex1.WeatherAPIProto.internal_static_extras_ex1_Temperature_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return uk.me.uohiro.protobuf.model.extras.ex1.WeatherAPIProto.internal_static_extras_ex1_Temperature_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            uk.me.uohiro.protobuf.model.extras.ex1.Temperature.class, uk.me.uohiro.protobuf.model.extras.ex1.Temperature.Builder.class);
  }

  /**
   * Protobuf enum {@code extras.ex1.Temperature.Units}
   */
  public enum Units
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>FAHRENHEIT = 0;</code>
     */
    FAHRENHEIT(0),
    /**
     * <code>CELCIUS = 1;</code>
     */
    CELCIUS(1),
    /**
     * <code>KELVIN = 2;</code>
     */
    KELVIN(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>FAHRENHEIT = 0;</code>
     */
    public static final int FAHRENHEIT_VALUE = 0;
    /**
     * <code>CELCIUS = 1;</code>
     */
    public static final int CELCIUS_VALUE = 1;
    /**
     * <code>KELVIN = 2;</code>
     */
    public static final int KELVIN_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Units valueOf(int value) {
      return forNumber(value);
    }

    public static Units forNumber(int value) {
      switch (value) {
        case 0: return FAHRENHEIT;
        case 1: return CELCIUS;
        case 2: return KELVIN;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Units>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Units> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Units>() {
            public Units findValueByNumber(int number) {
              return Units.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return uk.me.uohiro.protobuf.model.extras.ex1.Temperature.getDescriptor().getEnumTypes().get(0);
    }

    private static final Units[] VALUES = values();

    public static Units valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Units(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:extras.ex1.Temperature.Units)
  }

  public static final int DEGREES_FIELD_NUMBER = 1;
  private float degrees_;
  /**
   * <code>float degrees = 1;</code>
   */
  public float getDegrees() {
    return degrees_;
  }

  public static final int UNITS_FIELD_NUMBER = 2;
  private int units_;
  /**
   * <code>.extras.ex1.Temperature.Units units = 2;</code>
   */
  public int getUnitsValue() {
    return units_;
  }
  /**
   * <code>.extras.ex1.Temperature.Units units = 2;</code>
   */
  public uk.me.uohiro.protobuf.model.extras.ex1.Temperature.Units getUnits() {
    @SuppressWarnings("deprecation")
    uk.me.uohiro.protobuf.model.extras.ex1.Temperature.Units result = uk.me.uohiro.protobuf.model.extras.ex1.Temperature.Units.valueOf(units_);
    return result == null ? uk.me.uohiro.protobuf.model.extras.ex1.Temperature.Units.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (degrees_ != 0F) {
      output.writeFloat(1, degrees_);
    }
    if (units_ != uk.me.uohiro.protobuf.model.extras.ex1.Temperature.Units.FAHRENHEIT.getNumber()) {
      output.writeEnum(2, units_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (degrees_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(1, degrees_);
    }
    if (units_ != uk.me.uohiro.protobuf.model.extras.ex1.Temperature.Units.FAHRENHEIT.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, units_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof uk.me.uohiro.protobuf.model.extras.ex1.Temperature)) {
      return super.equals(obj);
    }
    uk.me.uohiro.protobuf.model.extras.ex1.Temperature other = (uk.me.uohiro.protobuf.model.extras.ex1.Temperature) obj;

    boolean result = true;
    result = result && (
        java.lang.Float.floatToIntBits(getDegrees())
        == java.lang.Float.floatToIntBits(
            other.getDegrees()));
    result = result && units_ == other.units_;
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + DEGREES_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getDegrees());
    hash = (37 * hash) + UNITS_FIELD_NUMBER;
    hash = (53 * hash) + units_;
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static uk.me.uohiro.protobuf.model.extras.ex1.Temperature parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static uk.me.uohiro.protobuf.model.extras.ex1.Temperature parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static uk.me.uohiro.protobuf.model.extras.ex1.Temperature parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static uk.me.uohiro.protobuf.model.extras.ex1.Temperature parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static uk.me.uohiro.protobuf.model.extras.ex1.Temperature parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static uk.me.uohiro.protobuf.model.extras.ex1.Temperature parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static uk.me.uohiro.protobuf.model.extras.ex1.Temperature parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static uk.me.uohiro.protobuf.model.extras.ex1.Temperature parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static uk.me.uohiro.protobuf.model.extras.ex1.Temperature parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static uk.me.uohiro.protobuf.model.extras.ex1.Temperature parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static uk.me.uohiro.protobuf.model.extras.ex1.Temperature parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static uk.me.uohiro.protobuf.model.extras.ex1.Temperature parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(uk.me.uohiro.protobuf.model.extras.ex1.Temperature prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code extras.ex1.Temperature}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:extras.ex1.Temperature)
      uk.me.uohiro.protobuf.model.extras.ex1.TemperatureOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return uk.me.uohiro.protobuf.model.extras.ex1.WeatherAPIProto.internal_static_extras_ex1_Temperature_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return uk.me.uohiro.protobuf.model.extras.ex1.WeatherAPIProto.internal_static_extras_ex1_Temperature_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              uk.me.uohiro.protobuf.model.extras.ex1.Temperature.class, uk.me.uohiro.protobuf.model.extras.ex1.Temperature.Builder.class);
    }

    // Construct using uk.me.uohiro.protobuf.model.extras.ex1.Temperature.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      degrees_ = 0F;

      units_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return uk.me.uohiro.protobuf.model.extras.ex1.WeatherAPIProto.internal_static_extras_ex1_Temperature_descriptor;
    }

    @java.lang.Override
    public uk.me.uohiro.protobuf.model.extras.ex1.Temperature getDefaultInstanceForType() {
      return uk.me.uohiro.protobuf.model.extras.ex1.Temperature.getDefaultInstance();
    }

    @java.lang.Override
    public uk.me.uohiro.protobuf.model.extras.ex1.Temperature build() {
      uk.me.uohiro.protobuf.model.extras.ex1.Temperature result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public uk.me.uohiro.protobuf.model.extras.ex1.Temperature buildPartial() {
      uk.me.uohiro.protobuf.model.extras.ex1.Temperature result = new uk.me.uohiro.protobuf.model.extras.ex1.Temperature(this);
      result.degrees_ = degrees_;
      result.units_ = units_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof uk.me.uohiro.protobuf.model.extras.ex1.Temperature) {
        return mergeFrom((uk.me.uohiro.protobuf.model.extras.ex1.Temperature)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(uk.me.uohiro.protobuf.model.extras.ex1.Temperature other) {
      if (other == uk.me.uohiro.protobuf.model.extras.ex1.Temperature.getDefaultInstance()) return this;
      if (other.getDegrees() != 0F) {
        setDegrees(other.getDegrees());
      }
      if (other.units_ != 0) {
        setUnitsValue(other.getUnitsValue());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      uk.me.uohiro.protobuf.model.extras.ex1.Temperature parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (uk.me.uohiro.protobuf.model.extras.ex1.Temperature) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private float degrees_ ;
    /**
     * <code>float degrees = 1;</code>
     */
    public float getDegrees() {
      return degrees_;
    }
    /**
     * <code>float degrees = 1;</code>
     */
    public Builder setDegrees(float value) {
      
      degrees_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float degrees = 1;</code>
     */
    public Builder clearDegrees() {
      
      degrees_ = 0F;
      onChanged();
      return this;
    }

    private int units_ = 0;
    /**
     * <code>.extras.ex1.Temperature.Units units = 2;</code>
     */
    public int getUnitsValue() {
      return units_;
    }
    /**
     * <code>.extras.ex1.Temperature.Units units = 2;</code>
     */
    public Builder setUnitsValue(int value) {
      units_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.extras.ex1.Temperature.Units units = 2;</code>
     */
    public uk.me.uohiro.protobuf.model.extras.ex1.Temperature.Units getUnits() {
      @SuppressWarnings("deprecation")
      uk.me.uohiro.protobuf.model.extras.ex1.Temperature.Units result = uk.me.uohiro.protobuf.model.extras.ex1.Temperature.Units.valueOf(units_);
      return result == null ? uk.me.uohiro.protobuf.model.extras.ex1.Temperature.Units.UNRECOGNIZED : result;
    }
    /**
     * <code>.extras.ex1.Temperature.Units units = 2;</code>
     */
    public Builder setUnits(uk.me.uohiro.protobuf.model.extras.ex1.Temperature.Units value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      units_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.extras.ex1.Temperature.Units units = 2;</code>
     */
    public Builder clearUnits() {
      
      units_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:extras.ex1.Temperature)
  }

  // @@protoc_insertion_point(class_scope:extras.ex1.Temperature)
  private static final uk.me.uohiro.protobuf.model.extras.ex1.Temperature DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new uk.me.uohiro.protobuf.model.extras.ex1.Temperature();
  }

  public static uk.me.uohiro.protobuf.model.extras.ex1.Temperature getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Temperature>
      PARSER = new com.google.protobuf.AbstractParser<Temperature>() {
    @java.lang.Override
    public Temperature parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Temperature(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Temperature> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Temperature> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public uk.me.uohiro.protobuf.model.extras.ex1.Temperature getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

