// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ch11/ex1/sfapi.proto

package uk.me.uohiro.protobuf.model.ch11.ex1;

public interface GetFilmRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ch11.ex1.GetFilmRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();
}
