// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ch11/ex1/sfapi.proto

package uk.me.uohiro.protobuf.model.ch11.ex1;

public interface ListFilmsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ch11.ex1.ListFilmsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .ch11.ex1.Film films = 1;</code>
   */
  java.util.List<uk.me.uohiro.protobuf.model.ch11.ex1.Film> 
      getFilmsList();
  /**
   * <code>repeated .ch11.ex1.Film films = 1;</code>
   */
  uk.me.uohiro.protobuf.model.ch11.ex1.Film getFilms(int index);
  /**
   * <code>repeated .ch11.ex1.Film films = 1;</code>
   */
  int getFilmsCount();
  /**
   * <code>repeated .ch11.ex1.Film films = 1;</code>
   */
  java.util.List<? extends uk.me.uohiro.protobuf.model.ch11.ex1.FilmOrBuilder> 
      getFilmsOrBuilderList();
  /**
   * <code>repeated .ch11.ex1.Film films = 1;</code>
   */
  uk.me.uohiro.protobuf.model.ch11.ex1.FilmOrBuilder getFilmsOrBuilder(
      int index);
}
