// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ch3/ex6.proto

package uk.me.uohiro.protobuf.model.ch3.ex6;

public interface GetFilmRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ch3.ex6.GetFilmRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required string id = 1;</code>
   */
  boolean hasId();
  /**
   * <code>required string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <code>required string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();
}
