// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ch3/ex6.proto

package uk.me.uohiro.protobuf.model.ch3.ex6;

public interface GetFilmResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ch3.ex6.GetFilmResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required .ch3.ex6.Film film = 1;</code>
   */
  boolean hasFilm();
  /**
   * <code>required .ch3.ex6.Film film = 1;</code>
   */
  uk.me.uohiro.protobuf.model.ch3.ex6.Film getFilm();
  /**
   * <code>required .ch3.ex6.Film film = 1;</code>
   */
  uk.me.uohiro.protobuf.model.ch3.ex6.FilmOrBuilder getFilmOrBuilder();
}
