// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ch3/ex15.proto

package uk.me.uohiro.protobuf.model.ch3.ex15;

public interface Test2OrBuilder extends
    // @@protoc_insertion_point(interface_extends:ch3.ex15.Test2)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required .ch3.ex15.Test1 value = 2;</code>
   */
  boolean hasValue();
  /**
   * <code>required .ch3.ex15.Test1 value = 2;</code>
   */
  uk.me.uohiro.protobuf.model.ch3.ex15.Test1 getValue();
  /**
   * <code>required .ch3.ex15.Test1 value = 2;</code>
   */
  uk.me.uohiro.protobuf.model.ch3.ex15.Test1OrBuilder getValueOrBuilder();
}
